include:
  - project: deliver/devops
    file: /deployment/templates/base.yml
  - project: deliver/devops
    file: /deployment/templates/commons.yml

stages:
  - resolve
  - build
  - deploy

variables:
  PROJECT_NAME: deliver-web
  KUSTOMIZE_DEPLOYMENT_PATH: deployment
  PROJECT_VERSION: $CI_COMMIT_SHORT_SHA

.docker-builder-prim:
  extends:
    - .shell-basic
  script:
    - unset https_proxy && unset http_proxy
    - if [ "$DOCKER_LOGIN_NEEDED" = true ] ; then docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $DOCKER_REPO; fi
    - docker build -t $DOCKER_REPO/$PROJECT_NAME:$PROJECT_VERSION .
    - docker push $DOCKER_REPO/$PROJECT_NAME:$PROJECT_VERSION

.deliver-web-builder:
  stage: build
  extends:
    - .docker-builder-prim

.deliver-web-deployer:
  stage: deploy
  extends:
    - .kustomize-deploy

resolve:
  stage: resolve
  extends:
    - .shell-basic
  script:
    - unset https_proxy && unset http_proxy
    - if [ "$DOCKER_LOGIN_NEEDED" = true ] ; then docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $DOCKER_REPO; fi
    - docker build -t $DOCKER_REPO/deliver-flutter-resolved:$PROJECT_VERSION -f resolver.dockerfile .
    - docker push $DOCKER_REPO/deliver-flutter-resolved:$PROJECT_VERSION

dev_build:
  needs: [ ]
  when: manual
  extends:
    - .only-master
    - .deliver-web-builder
    - .dev

dev_deploy:
  needs: [ dev_build ]
  when: manual
  extends:
    - .only-master
    - .deliver-web-deployer
    - .dev

android_build:
  stage: build
  needs: [ resolve ]
  image: $DOCKER_REPO/deliver-flutter-resolved:$PROJECT_VERSION
  extends:
    - .docker-basic
  script:
    - flutter build appbundle --target-platform android-arm --build-name=1.9.1 --build-number=61
  artifacts:
    paths:
      - /usr/local/bin/app/build/app/outputs/bundle/release/app-release.aab
    expire_in: 1 week

prod_build:
  needs: [ ]
  extends:
    - .only-master
    - .deliver-web-builder
    - .prod

prod_deploy:
  needs: [ prod_build ]
  extends:
    - .only-master
    - .deliver-web-deployer
    - .prod