include:
  - project: deliver/gitlab-templates
    file: flutter.gitlab-ci.yml


variables:
  PROJECT_NAME: deliver-web
  PROJECT_VERSION: $CI_COMMIT_SHORT_SHA
  RESOLVER_VERSION: 2
  PROJECT_BUILD_NAME: "1.9.2"
  PROJECT_BUILD_NUMBER: "62"

fake-test:
  extends: [ .test-definition ]
  script:
    - echo "Flutter Test not passing for Now"
#    - flutter test

publish-we-android:
  extends: [ .publish-android-definition ]
