include:
  - project: deliver/devops
    file: /deployment/templates/base.yml
  - project: deliver/devops
    file: /deployment/templates/commons.yml

stages:
  - resolve
  - build
  - deploy

variables:
  PROJECT_NAME: deliver-web
  KUSTOMIZE_DEPLOYMENT_PATH: deployment
  PROJECT_VERSION: $CI_COMMIT_SHORT_SHA
  RESOLVER_VERSION: 2
  PROJECT_BUILD_NAME: "1.9.1"
  PROJECT_BUILD_NUMBER: "61"

.docker-builder-prim:
  extends:
    - .shell-basic
  script:
    - unset https_proxy && unset http_proxy
    - if [ "$DOCKER_LOGIN_NEEDED" = true ] ; then docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $DOCKER_REPO; fi
    - docker build -t $DOCKER_REPO/$PROJECT_NAME:$PROJECT_VERSION .
    - docker push $DOCKER_REPO/$PROJECT_NAME:$PROJECT_VERSION

.deliver-web-builder:
  stage: build
  extends:
    - .docker-builder-prim

.deliver-web-deployer:
  stage: deploy
  extends:
    - .kustomize-deploy

resolve:
  stage: resolve
  extends:
    - .shell-basic
  script:
    - unset https_proxy && unset http_proxy
    - if [ "$DOCKER_LOGIN_NEEDED" = true ] ; then docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $DOCKER_REPO; fi
    - docker build -t $DOCKER_REPO/deliver-flutter-resolved:$RESOLVER_VERSION -f resolver.dockerfile .
    - docker push $DOCKER_REPO/deliver-flutter-resolved:$RESOLVER_VERSION

dev_build:
  needs: [ ]
  when: manual
  extends:
    - .only-master
    - .deliver-web-builder
    - .dev

dev_deploy:
  needs: [ dev_build ]
  when: manual
  extends:
    - .only-master
    - .deliver-web-deployer
    - .dev

android_build:
  stage: build
  timeout: 6h
  needs: [ resolve ]
  image: $DOCKER_REPO/deliver-flutter-resolved:$RESOLVER_VERSION
  variables:
    _JAVA_OPTIONS: "-Xmx2048m -XX:+UnlockExperimentalVMOptions"
    GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m"'
  extends:
    - .docker-basic
  script:
    - cd /usr/local/bin/app/
    - flutter build appbundle --target-platform android-arm --build-name=$PROJECT_BUILD_NAME --build-number=$PROJECT_BUILD_NUMBER
    - flutter build apk --split-per-abi
  cache:
    key: "$CI_COMMIT_REF_NAME"
    when: always
    untracked: true
    paths:
      - /root/.gradle/
      - /root/.pub-cache/
  artifacts:
    paths:
      - /usr/local/bin/app/build/app/outputs/bundle/release/app-release.aab
      - /usr/local/bin/app/build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
    expire_in: 1 week

prod_build:
  needs: [ ]
  when: manual
  extends:
    - .only-master
    - .deliver-web-builder
    - .prod

prod_deploy:
  needs: [ prod_build ]
  extends:
    - .only-master
    - .deliver-web-deployer
    - .prod