# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

# build appbundle --target-platform android-arm,android-arm64,android-x64

name: deliver
description: Messenger App

# PUBSPEC VERSION
version: 2.1.0  #if change the version , is necessary to change VERSION  in constants.dart

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  all_sensors: 0.4.2
  android_intent_plus: 3.1.6
  animate_do: 3.0.2
  animations: 2.0.7
  audioplayers: 3.0.1
  badges: 3.0.2
  brotli: 0.5.0
  camera: 0.10.3+1
  card_swiper: 2.0.4
  chewie: 1.4.0
  circular_countdown_timer: 0.2.3
  clock: 1.1.1
  collection: 1.17.0
  connectivity_plus: 3.0.3
  connectycube_flutter_call_kit:
    git:
      ref: 49be185aefaf6ae910f7359306ec12423d443efa
      url: https://github.com/deliveriais/connectycube_flutter_call_kit
  custom_image_crop: 0.0.4
  dart_vlc: 0.4.0
  date_time_format: 2.0.1
  dcache: 0.4.0
  deliver_public_protocol:
    git:
      ref: tags/v1.12.21
      url: https://github.com/deliver-iais/pub-dart-artifactory
  desktop_drop: 0.4.1
  desktop_lifecycle: 0.1.0
  desktop_window:
    git:
      ref: main
      url: https://github.com/deliveriais/desktop_window
  device_info: 2.0.3
  dio: 5.0.1
  dismissible_page: 1.0.1
  expandable: 5.0.1
  extended_image: 7.0.2
  fast_contacts: 3.0.3
  feature_discovery:
    git:
      ref: 319d1fe74fcee87eef427a6136639b3bf2537a89
      url: https://github.com/deliveriais/feature_discovery
  file_picker: 5.2.5
  file_selector: 0.9.2+3
  file_selector_linux: 0.9.1+1
  firebase_analytics: 10.1.4
  firebase_core: 2.7.0
  #  firebase_crashlytics: 3.0.12
  firebase_messaging: 14.2.5
  fixnum: 1.1.0
  flutter:
    sdk: flutter
  flutter_app_badger: 1.5.0
  flutter_audio_waveforms: 1.2.1+8
  flutter_blurhash: 0.7.0
  flutter_dropzone: 3.0.5
  flutter_foreground_task: 4.1.0
  flutter_image_compress: 1.1.3
  flutter_keyboard_visibility: 5.4.0
  flutter_local_notifications: 13.0.0
  flutter_localizations:
    sdk: flutter
  flutter_map: 3.1.0
  flutter_webrtc: 0.9.23
  fluttertoast: 8.2.1
  font_awesome_flutter: 10.4.0
  fuzzy: 0.4.0-nullsafety.0
  gallery_saver: 2.3.2
  geolocator: 9.0.2
  get_it: 7.2.0
  google_fonts: 4.0.3
  great_list_view: 0.2.3
  grpc:
    git:
      ref: master
      url: https://github.com/deliveriais/grpc-dart
  hive: 2.2.3
  hive_flutter: 1.1.0
  hovering: 1.0.4
  http: 0.13.5
  http_parser: 4.0.2
  image: 3.3.0
  image_compression_flutter: 1.0.2
  image_cropper: 3.0.1
  image_size_getter: 2.1.2
  intl: 0.17.0
  js: 0.6.5
  just_audio: 0.9.31
  jwt_decoder: 2.0.1
  latlong2: 0.8.1
  livekit_client: 1.2.0
  logger: 1.2.2
  lottie: 2.2.0
  map_launcher: 2.5.0+1
  marquee: 2.2.3
  material_color_utilities: 0.2.0
  meta: 1.8.0
  metadata_fetch: 0.4.1
  mime: 1.0.4
  mobile_scanner: 3.0.0
  modal_bottom_sheet: 3.0.0-pre
  open_filex: 4.3.2
  pasteboard: 0.2.0
  path: 1.8.2
  path_provider: 2.0.13
  path_provider_android: 2.0.23
  patterns_canvas: 0.4.0 # UPDATABLE in FLUTTER 3
  percent_indicator: 4.2.2
  permission_handler: 10.2.0
  persian_datetime_picker: 2.5.0
  phone_state: 1.0.2
  photo_manager: 2.5.2
  photo_view: 0.14.0
  pinput: 2.2.31
  platform_detect: 2.0.7
  process_run: 0.12.5+2
  provider: 6.0.5
  qr_flutter: 4.0.0
  random_string: 2.3.1
  receive_sharing_intent: 1.4.5
  record: 4.4.4
  rive: 0.10.2
  rxdart: 0.27.7
  screenshot: 1.3.0
  scrollable_positioned_list:
    git:
      path: packages/scrollable_positioned_list
      ref: 775e1a365637f4e625cf042be383e0d601ab13be
      url: https://github.com/deliveriais/flutter.widgets
  sdp_transform: 0.3.2
  sensors_plus: 2.0.2
  service_worker: 0.3.0
  share: 2.0.4
  shared_preferences: 2.0.18
  shimmer: 2.0.0
  simple_animations: 5.0.0+3
  sms_autofill: 2.3.0
  synchronized: 3.0.1
  telephony:
    git:
      ref: fdf93b3dc72ff7a911de0ce187949338486753e7
      url: https://github.com/EsmaeilDansi/Telephony.git
  tuple: 2.0.1
  universal_html: 2.0.9
  url_launcher: 6.1.10
  uuid: 3.0.7
  vibration: 1.7.6
  video_player: 2.5.2
  wakelock: 0.6.2
  win_toast:
    git:
      path: packages/win_toast
      ref: 5357c2a594a20534bf759eb28c86f8669d3914f3
      url: https://github.com/deliveriais/flutter-plugins
  window_size:
    git:
      path: plugins/window_size
      ref: 5c51870ced62a00e809ba4b81a846a052d241c9f
      url: https://github.com/google/flutter-desktop-embedding
  workmanager: 0.5.1


dev_dependencies:
  build_runner: 2.3.3

  dependency_validator: 3.2.2  # flutter pub run dependency_validator
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter
  hive_generator: 2.0.0

  integration_test:
    sdk: flutter
  mockito: 5.3.2



# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - android/app/src/main/res/raw/
    - assets/animations/
    - assets/audios/beep_sound.mp3
    - assets/audios/busy_sound.mp3
    - assets/audios/incoming_msg.mp3
    - assets/audios/incoming_call.mp3
    - assets/audios/sound_in.wav
    - assets/audios/sound_out.wav
    - assets/backgrounds/
    - assets/emoji/
    - assets/ic_launcher/res/mipmap-xxxhdpi/ic_launcher.png
    - assets/images/logo.webp
    - assets/images/no-profile-pic.png
    - assets/images/security.webp
    - assets/images/experiment.webp
    - assets/images/language.webp
    - assets/images/connection.webp
    - lib/lang/en.json
    - lib/lang/fa.json
    - assets/audios/end_call.mp3
    - assets/duck_animation/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts: [ ]
