# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

# build appbundle --target-platform android-arm,android-arm64,android-x64

name: deliver
description: Messenger App

# PUBSPEC VERSION
version: 2.1.0  #if change the version , is necessary to change VERSION  in constants.dart

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.10.0-0"

dependencies:
  all_sensors2: 1.0.1
  android_intent: 2.0.2
  audioplayers: 0.20.1
  badges: 2.0.2
  camera: 0.9.4+17
  card_swiper: 2.0.3
  chewie: 1.3.1
  circular_countdown_timer: 0.2.1
  clock: 1.1.0
  collection: 1.15.0
  connectycube_flutter_call_kit:
    git:
      ref: bdec48f4f29857be6f8d3f3cf181bc22adbed325
      url: https://github.com/androidwoman/connectycube_flutter_call_kit2.0.5.git
  contacts_service: 0.6.3
  custom_image_crop: 0.0.4
  date_time_format: 2.0.1
  dcache: 0.4.0
  deliver_public_protocol:
    git:
      ref: tags/v1.12.13-rc.11
      url: https://github.com/deliver-iais/pub-dart-artifactory
  desktop_drop: 0.3.3
  desktop_lifecycle: 0.1.0
  desktop_window:
    git:
      ref: main
      url: https://github.com/deliver-iais/desktop_window
  device_info: 2.0.3
  dio: 4.0.3
  expandable: 5.0.1
  feature_discovery: 0.14.1
  file_picker: 4.5.1
  file_selector: 0.8.2+1
  file_selector_linux: 0.0.2+1
  firebase_analytics: 9.1.8
  firebase_core: 1.12.0
  firebase_messaging: 11.3.0
  #  firebase_messaging:
  #    git:
  #      ref: 7fcaebdf56e7285014422e7e484ce0c2ec403d24
  #      url: https://github.com/deliver-iais/firebase-messaging
  fixnum: 1.0.0
  flare_flutter: 3.0.2
  flutter:
    sdk: flutter
  flutter_audio_waveforms: 1.2.1+5
  flutter_blurhash: 0.6.4
  flutter_dropzone: 3.0.3
  flutter_foreground_task: 3.7.3
  flutter_image_compress: 1.1.0
  flutter_keyboard_visibility: 5.1.1
  flutter_local_notifications: 10.0.0-dev.13
  flutter_localizations:
    sdk: flutter
  flutter_map: 0.14.0
  flutter_webrtc:
    git:
      ref: 31051218d1068b5f2566f1646ca2623d2ea89697
      url: https://github.com/flutter-webrtc/flutter-webrtc
  fluttertoast: 8.0.8
  fuzzy: 0.4.0-nullsafety.0
  geolocator: 8.2.1
  get_it: 7.2.0
  google_fonts: 2.3.1
  great_list_view: 0.1.4
  grpc:
    git:
      ref: 29af7df647c0999a41c6b4186de8709574d81de5
      url: https://github.com/deliver-iais/grpc-dart
  hive: 2.1.0
  hive_flutter: 1.1.0
  hovering: 1.0.4
  http: 0.13.4
  http_parser: 4.0.0
  image_compression_flutter: 1.0.2
  image_picker: 0.8.4+11
  image_size_getter: 1.0.0
  intl: 0.17.0
  js: 0.6.3
  jwt_decoder: 2.0.1
  latlong2: 0.8.1
  logger: 1.1.0
  lottie: 1.2.2
  marquee: 2.2.1
  material_color_utilities: 0.1.3
  meta: 1.7.0
  metadata_fetch: 0.4.1
  mime_type: 1.0.0
  modal_bottom_sheet: 2.0.1
  open_file: 3.2.1
  package_info_plus: 1.4.0
  pasteboard: 0.0.3
  path: 1.8.0
  path_provider: 2.0.7
  path_provider_android: 2.0.11
  percent_indicator: 3.4.0
  permission_handler:
    git:
      path: permission_handler
      ref: b70197d0ef91c8ced58d894573df96e1ba3080d2
      url: https://github.com/AmirhosseinShk/flutter-permission-handler
  persian_datetime_picker: 2.4.0
  photo_manager: 2.1.1
  platform_detect: 2.0.0
  process_run: 0.12.3+2
  qr_code_scanner: 0.7.0
  qr_flutter: 4.0.0
  random_string: 2.3.1
  receive_sharing_intent: 1.4.5
  record: 3.0.4
  rxdart: 0.27.3
  screenshot: 1.2.3
  scrollable_positioned_list: 0.2.3
  sdp_transform: 0.3.2
  service_worker: 0.2.4
  share: 2.0.4
  simple_animations: 4.0.2
  sms_autofill: 2.2.0
  synchronized: 3.0.0+2
  tuple: 2.0.0
  uni_links: 0.5.1
  universal_html: 2.0.8
  url_launcher: 6.0.20
  vibration: 1.7.4-nullsafety.0
  video_player: 2.3.0
  wakelock: 0.6.1+1
  # if want increse flutter_webrtc version we should remove this line and let get it from parent
  #  webrtc_interface: 1.0.3
  win_toast:
    git:
      path: packages/win_toast
      ref: 5357c2a594a20534bf759eb28c86f8669d3914f3
      url: https://github.com/AmirhosseinShk/flutter-plugins
  window_size:
    git:
      path: plugins/window_size
      ref: e48abe7c3e9ebfe0b81622167c5201d4e783bb81
      url: https://github.com/google/flutter-desktop-embedding


dev_dependencies:
  build_runner: 2.1.8
  dependency_validator: 3.1.2  # flutter pub run dependency_validator
  flutter_lints: 1.0.4
  hive_generator: 1.1.2
  mockito: 5.1.0
  msix: 3.1.0
  test: 1.20.2

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - android/app/src/main/res/raw/
    - assets/animations/accept_call.json
    - assets/animations/arrow.json
    - assets/animations/audio_wave.tgs
    - assets/animations/clock.json
    - assets/animations/lock.json
    - assets/animations/done.tgs
    - assets/animations/file-save.json
    - assets/animations/not-found.tgs
    - assets/animations/touch.zip
    - assets/animations/unlock.tgs
    - assets/audios/beep_sound.mp3
    - assets/audios/busy_sound.mp3
    - assets/audios/incoming_call.mp3
    - assets/audios/incoming_msg.mp3
    - assets/audios/sound_in.wav
    - assets/audios/sound_out.wav
    - assets/backgrounds/
    - assets/emoji/
    - assets/ic_launcher/res/mipmap-xxxhdpi/ic_launcher.png
    - assets/images/a.flr
    - assets/images/logo.png
    - assets/images/no-profile-pic.png
    - assets/images/wave.png
    - lib/lang/en.json
    - lib/lang/fa.json
    - assets/animations/end_of_call.json
    - assets/audios/end_call.mp3
    - assets/animations/new_version.zip
    - assets/animations/out_of_date.zip
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Vazir
      fonts:
        - asset: assets/fonts/vazir/Vazir-Variable.ttf
