name: deliver_flutter
description: Messenger App

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

# build appbundle --target-platform android-arm,android-arm64,android-x64
version: 1.2.9

environment:
  sdk: ">=2.7.0 <3.0.0"

dependency_overrides:
  http: ^0.13.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_link_preview: 1.5.6

  carousel_slider: 2.3.1
  dots_indicator: 1.2.0

  flare_flutter: 2.0.6 # Animation Viewer Library
  date_time_format: 1.0.0+4

  emojis:
  permissions_plugin: 1.1.4 # ANDROID ONLY SUPPORTED
  synchronized: 3.0.0
  ext_storage: 1.0.3
  path_provider: 2.0.2
  path:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: 1.0.0

  get_it: # Dependency Injector Library
  rxdart: 0.26.0 # State Management Library & Advanced Streaming Library
  auto_route: 0.6.9 # Routing Library
  flutter_isolate: 2.0.0

  url_launcher: 6.0.4

  linkify: 3.0.0

  flutter_map: 0.13.1

  geolocator: ^5.1.3

  file_picker:

  path_provider_ex: ^1.0.1

  overlay_support:

  flutter_file_manager: ^0.2.0

  android_intent: 0.3.7+7

  window_size: # (DESKTOP ONLY) Setting min and max window size in desktop
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: e48abe7c3e9ebfe0b81622167c5201d4e783bb81

  file_selector: 0.8.2
  file_selector_macos: 0.0.4
  file_selector_linux: 0.0.2
  file_selector_windows: 0.0.2

  dio: 4.0.0 # HTTP Invoker Library
  mime_type: 0.3.2 # Get mime type of file path
  jwt_decoder: 1.0.1
  deliver_public_protocol: # DELIVER PROJECT PUBLIC GRPC PROTOCOL
    git:
      url: https://gitlab.iais.co/deliver-public/pub-dart-artifactory
      ref: tags/v1.7.0-rc.85
  grpc: 3.0.0 # (WEB NOT SUPPORTED BI-Directional Streaming)
  protobuf: 2.0.0 # (WEB NOT SUPPORTED BI-Directional Streaming)
  storage_path: 0.2.0 # (DESKTOP NOT SUPPORTED, BACKUP PLAN: FILE CHOOSER)
  image_picker: 0.8.0+3 # (DESKTOP NOT SUPPORTED, BACKUP PLAN: ?) -> CAMERA
  image_cropper: 1.3.1 # (DESKTOP NOT SUPPORTED, NO BACKUP PLAN)
 # image: ^2.1.19
  vibration: 1.7.2 # (DESKTOP NOT SUPPORTED, NO BACKUP NEEDED)
  dcache: 0.3.0

  image_size_getter: 0.2.1

  sqflite_common_ffi: 2.0.0+1

  audioplayer: 0.8.1
  audioplayers: 0.19.0

  video_player: 1.0.1
  open_file: 3.2.1 # Open file in OS
  package_info_plus: 1.0.3

  contacts_service: 0.6.1
  random_string: 2.1.0
  flutter_local_notifications: 6.0.0

#  flutter_timer: 0.0.6
  uuid: 3.0.4
  flutter_sound: 8.1.4

  record: 2.1.1
  percent_indicator: 2.1.8
  package_info: 2.0.2
  cached_network_image: 3.0.0

  moor: 4.3.2 # Multi-Platform ORM
  sqlite3_flutter_libs: 0.2.0 # Moor Needed Library
  sms_autofill: 1.2.6
  sorted_list: 1.0.0
  scrollable_positioned_list: 0.1.10
  share: 2.0.4
  fluttertoast: ^3.1.3
  firebase_messaging: 10.0.1
  firebase_core: 1.2.1
  flutter_swiper: 1.1.6
  ## mockito: 5.0.10 # Great Library for Mocking in Tests
  test:
  badges: 1.1.4

  modal_bottom_sheet: 2.0.0

  receive_sharing_intent: 1.4.5

  flutter_icons: 1.1.0
  desktop_notifications: 0.5.0


  assets_audio_player: 3.0.3+3

  flutter_parsed_text: 1.2.5

  device_info: 2.0.2

  hive: 2.0.4
  hive_flutter: 1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  moor_generator: 4.3.1
  marquee: 2.1.0
  build_runner:
  hive_generator: ^1.1.0
#  auto_route_generator:


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/a.flr
    - assets/ic_launcher/res/mipmap-xxxhdpi/ic_launcher.png
    - assets/icons/stickerIcon.png
    - assets/icons/emojiIcon.png
    - assets/audios/r.mp3
    - assets/audios/ack.mp3
    - lib/lang/fa.json
    - lib/lang/en.json
    - assets/icons/mention.png
    - assets/icons/channel_icon.png
    - assets/bac/bdark.jpg
    - assets/bac/b2.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Vazir
      fonts:
        - asset: assets/fonts/vazir/Vazir.ttf
        - asset: assets/fonts/vazir/Vazir-Bold.ttf
        - asset: assets/fonts/vazir/Vazir-Light.ttf
        - asset: assets/fonts/vazir/Vazir-Medium.ttf
        - asset: assets/fonts/vazir/Vazir-Thin.ttf
          weight: 700
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
#analyzer:
#  strong-mode: true
#  language:
#    enableSuperMixins: true