# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

# build appbundle --target-platform android-arm,android-arm64,android-x64

name: deliver
description: Messenger App

# PUBSPEC VERSION
version: 2.1.0  #if change the version , is necessary to change VERSION  in constants.dart

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependency_overrides:
  freezed_annotation: 2.2.0
  # Can be removed when
  # https://github.com/creativecreatorormaybenot/wakelock/pull/203 is merged.
  wakelock_windows:
    git:
      url: https://github.com/chandrabezzo/wakelock.git # repository
      ref: main # branch
      path: wakelock_windows/ # folder

dependencies:
  encrypt: ^5.0.3
  all_sensors: 0.4.2
  android_intent_plus: ^4.0.2
  animate_do: ^3.1.2
  animations: ^2.0.8
  audioplayers:
    git:
      ref: main
#      path: packages/audioplayers
      url: https://github.com/EsmaeilDansi/audio_players
  aurora: 1.0.0
  background_sms: 0.0.4
  badges: ^3.1.2
  battery_plus: 3.0.3
  brotli: ^0.6.0
  browser_image_compression:
    git:
      ref: 6805a29e07d95fab29392654afddfc225020a5e5
      url: https://github.com/deliveriais/browser_image_compression.git
  camera: ^0.10.5+9
  card_swiper: ^3.0.1
  chewie: ^1.7.1
  circular_countdown_timer: 0.2.3
  clock: 1.1.1
  collection: ^1.17.2
  confetti: 0.7.0
  connectivity_plus: ^4.0.2
  connectycube_flutter_call_kit:
    git:
      ref: 49be185aefaf6ae910f7359306ec12423d443efa
      url: https://github.com/deliveriais/connectycube_flutter_call_kit
  custom_image_crop: ^0.0.12
  dart_vlc: 0.4.0
  date_time_format: 2.0.1
  ecache: 2.0.3

  deliver_public_protocol:
    git:
      ref: tags/v1.15.77
      url: https://github.com/deliver-iais/pub-dart-artifactory
  desktop_drop: 0.4.1
  desktop_lifecycle: ^0.1.1
  desktop_window:
    git:
      ref: main
      url: https://github.com/deliveriais/desktop_window
  device_info_plus: 9.0.2
  image_gallery_saver: 2.0.3
  dio: ^5.3.3
  dismissible_page: 1.0.2
  expandable: 5.0.1
  extended_image: 8.1.1
  fast_contacts: 3.0.3
  feature_discovery:
    git:
      ref: 319d1fe74fcee87eef427a6136639b3bf2537a89
      url: https://github.com/deliveriais/feature_discovery
  file_picker: 5.3.0
  file_selector: 0.9.2+3
  file_selector_linux: 0.9.1+1
  firebase_analytics: 10.2.1
  firebase_core: 2.10.0
  firebase_core_platform_interface: 4.6.0
  #  firebase_crashlytics: 3.0.12
  firebase_messaging: 14.4.1
  fixnum: 1.1.0
  flip_panel_plus: 1.0.0+3
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0+1
  flutter_app_badger: 1.5.0
  flutter_audio_waveforms: 1.2.1+8
  flutter_blurhash_plus: 0.8.0
  flutter_dropzone: ^3.0.6
  flutter_foreground_task: ^6.0.0+1
  flutter_image_compress: 1.1.3
  flutter_inappwebview: 6.0.0-beta.23
  flutter_keyboard_visibility: ^5.4.1
  flutter_local_notifications: ^16.1.0
  flutter_localizations:
    sdk: flutter
  flutter_map: 6.0.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_video_info: 1.3.1
  flutter_webrtc: 0.9.45
  flutter_window_close: 0.2.2
  fluttertoast: ^8.2.2
  font_awesome_flutter: ^10.5.0
  freezed_annotation: 2.2.0
  fuzzy: ^0.5.0
  geolocator: ^10.1.0
  get: 4.6.6
  get_it: ^7.6.4
  google_api_availability_android:
    git:
      path: google_api_availability_android
      ref: 6b3c18b8b615146488a2d5b8ea468416144252d5
      url: https://github.com/deliveriais/flutter-google-api-availability
  google_api_availability_platform_interface:
    git:
      path: google_api_availability_platform_interface
      ref: 1ebed7a8874f1581fcf24adaa9483cd62662734d
      url: https://github.com/deliveriais/flutter-google-api-availability
  google_fonts: ^4.0.4
  great_list_view: 0.2.3
  grpc:
    git:
      ref: 9ccedde33198072a22c3d2a3cc46fcc2307ada60
      url: https://github.com/deliveriais/grpc-dart
  hive: 2.2.3
  hive_flutter: 1.1.0
  hovering: 1.0.4
  http_parser: 4.0.2
  idb_shim: 2.3.1
  image: ^4.1.3
  image_compression: ^1.0.4
  image_compression_flutter: ^1.0.3
  image_cropper: 5.0.0
  image_size_getter: 2.1.2
  intl: ^0.18.1
  isar: 3.1.0+1
  isar_flutter_libs: 3.1.0+1
  js: 0.6.7
  json_annotation: ^4.8.1
  just_audio: ^0.9.35
  jwt_decoder: 2.0.1
  latlong2: ^0.9.0
  livekit_client: 1.5.2
  logger: ^2.0.2+1
  lottie: ^2.6.0
  map_launcher: 2.5.0+1
  marquee: 2.2.3
  material_color_utilities: ^0.5.0
  meta: 1.10.0
  metadata_fetch:
    git:
      ref: 422b4113f75db7c076fdd8b23437d4fb02b32f6e
      url: https://github.com/EsmaeilDansi/metadata_fetch
  mime: 1.0.4
  mobile_scanner: 3.0.0
  modal_bottom_sheet: 3.0.0-pre
  network_info_plus: 4.1.0
  open_filex: 4.3.2
  get_ip_address: ^0.0.6
  pasteboard: 0.2.0
  path: 1.8.3
  path_provider: ^2.1.1
  widgets_to_image: 0.0.2
  path_provider_android: ^2.2.0
  patterns_canvas: 0.4.0 # UPDATABLE in FLUTTER 3
  percent_indicator: 4.2.3
  permission_handler: ^11.0.1
  persian_datetime_picker:
    git:
      ref: master
      url: https://github.com/deliveriais/persian-datetime-picker
  persian_number_utility: 1.1.3
  phone_state: ^1.0.3
  photo_manager: ^3.0.0-dev.5
  photo_view: 0.14.0
  dropdown_search: 5.0.6
  pinput: ^3.0.1
  platform_detect: ^2.0.11
  process_run: ^0.13.1

  provider: 6.0.5
  qr_flutter: ^4.1.0
  random_string: 2.3.1
  receive_sharing_intent: 1.4.5
  record: 4.4.4
  rive: 0.12.4
  rxdart: 0.27.7
  screenshot:
    git:
      ref: master
      url: https://github.com/deliveriais/screenshot
  scrollable_positioned_list:
    git:
      path: packages/scrollable_positioned_list
      ref: 775e1a365637f4e625cf042be383e0d601ab13be
      url: https://github.com/deliveriais/flutter.widgets
  sdp_transform: 0.3.2
  http: 1.1.2
  sensors_plus: ^3.0.3
  service_worker: 0.3.0
  share: 2.0.4
  shared_preferences: ^2.2.1
  shimmer: 3.0.0
  simple_animations: ^5.0.2
  smooth_page_indicator: 1.1.0
  sms_autofill: 2.3.0
  synchronized: ^3.1.0
  telephony:
    git:
      ref: fdf93b3dc72ff7a911de0ce187949338486753e7
      url: https://github.com/EsmaeilDansi/Telephony.git
  tuple: ^2.0.2
  universal_html: 2.2.3
  url_launcher: ^6.1.14
  uuid: 3.0.7
  vibration: ^1.8.2
  video_player: ^2.7.2
  wakelock: 0.6.2
  win_toast:
    git:
      path: packages/win_toast
      ref: 5357c2a594a20534bf759eb28c86f8669d3914f3
      url: https://github.com/deliveriais/flutter-plugins
  window_size:
    git:
      path: plugins/window_size
      ref: 5c51870ced62a00e809ba4b81a846a052d241c9f
      url: https://github.com/google/flutter-desktop-embedding
  workmanager: 0.5.1


dev_dependencies:
  build_runner: ^2.4.6 # flutter pub run build_runner build --delete-conflicting-outputs
  dart_code_metrics:
    git:
      url: https://github.com/EsmaeilDansi/dart-code-metrics
      ref: 53b257a55915feec6c581356baf83babd497e340

  dependency_validator: ^3.2.3  # flutter pub run dependency_validator
  flutter_lints: 3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  hive_generator: ^2.0.1
  integration_test:
    sdk: flutter
  isar_generator: 3.1.0+1
  json_serializable: ^6.7.1
  mockito: ^5.4.2



# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - android/app/src/main/res/raw/
    - assets/animations/
    - assets/audios/beep_sound.mp3
    - assets/audios/busy_sound.mp3
    - assets/audios/incoming_msg.mp3
    - assets/audios/incoming_call.mp3
    - assets/audios/sound_in.wav
    - assets/audios/sound_out.wav
    - assets/backgrounds/
    - assets/emoji/
    - assets/ic_launcher/res/mipmap-xxxhdpi/ic_launcher.png
    - assets/ic_launcher/res/mipmap-xxxhdpi/ic_local_network.png
    - assets/images/logo.webp
    - assets/images/no-profile-pic.png
    - assets/images/security.webp
    - assets/images/experiment.webp
    - assets/images/language.webp
    - assets/images/connection.webp
    - assets/images/norouz.webp
    - lib/lang/en.json
    - lib/lang/fa.json
    - lib/lang/ar.json
    - assets/audios/end_call.mp3
    - assets/duck_animation/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts: [ ]
