name: deliver
description: Messenger App

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

# build appbundle --target-platform android-arm,android-arm64,android-x64

version: 1.4.6    #if change the version , is necessary to change VERSION  in constants.dart

environment:
  sdk: ">=2.7.0 <3.0.0"
# subject=C = IR, ST = Deliver, L = TE, O = IAIS, OU = Deliver, CN = Deliver, emailAddress = e.dansi.111@gmail.com
msix_config:
  display_name: Deliver
  publisher_display_name: Deliver
  identity_name: Deiver
  msix_version: 1.0.0.0
  certificate_path: C:\Deliver\CERTIFICATE.pfx
  certificate_password: 96112049
  publisher: CN=Deliver, O=IAIS, C=IR
  logo_path: C:\Deliver\deliver.png
  start_menu_icon_path: C:\Deliver\deliver.png
  tile_icon_path: C:\Deliver\deliver.png
  architecture: x64

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  desktoasts: 0.0.2
  carousel_slider: 2.3.1
  dots_indicator: 1.2.0
  flare_flutter: 2.0.6 # Animation Viewer Library
  lottie: 1.1.0
  date_time_format: 1.0.0+4
  emojis:
  permission_handler: 8.1.6 # ANDROID ONLY SUPPORTED
  synchronized: 3.0.0
  ext_storage: 1.0.3
  path_provider: 2.0.2
  path:
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: 1.0.0
  get_it: # Dependency Injector Library
  rxdart: 0.26.0 # State Management Library & Advanced Streaming Library
  auto_route: 0.6.9 # Routing Library
  flutter_isolate: 2.0.0
  url_launcher: 6.0.4
  qr_code_scanner: 0.4.0
  linkify: 3.0.0
  uni_links: 0.5.1
  flutter_map: 0.13.1
  geolocator: 7.0.1
  file_picker:
  logger: 1.0.0
  overlay_support:
  flutter_file_manager: ^0.2.0
  android_intent: 0.3.7+7
  settings_ui: 1.0.0
  window_size: # (DESKTOP ONLY) Setting min and max window size in desktop
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: e48abe7c3e9ebfe0b81622167c5201d4e783bb81
  file_selector: 0.8.2
  file_selector_macos: 0.0.4
  file_selector_linux: 0.0.2
  file_selector_windows: 0.0.2
  dio: 4.0.0 # HTTP Invoker Library
  mime_type: 1.0.0 # Get mime type of file path
  jwt_decoder: 1.0.1 # TODO, read documentation and update it
  deliver_public_protocol: # DELIVER PROJECT PUBLIC GRPC PROTOCOL
    git:
      url: https://github.com/deliver-iais/pub-dart-artifactory
      ref: tags/v1.9.0
  grpc: 3.0.2 # (WEB NOT SUPPORTED BI-Directional Streaming)
  protobuf: 2.0.0 # (WEB NOT SUPPORTED BI-Directional Streaming)
  storage_path: 0.2.0 # (DESKTOP NOT SUPPORTED, BACKUP PLAN: FILE CHOOSER)
  image_picker: 0.8.0+3 # (DESKTOP NOT SUPPORTED, BACKUP PLAN: ?) -> CAMERA
  image_cropper: 1.4.1 # (DESKTOP NOT SUPPORTED, NO BACKUP PLAN)
  vibration: 1.7.3 # (DESKTOP NOT SUPPORTED, NO BACKUP NEEDED)
  dcache: 0.4.0
  image_size_getter: 0.2.1
  swipe_to: 0.0.1+8
#  google_maps_place_picker: 2.0.0-nullsafety.3
  audioplayers: 0.20.1
  dart_vlc: 0.0.9
  video_player: 2.2.4
  open_file: 3.2.1 # Open file in OS
  contacts_service: 0.6.1
  random_string: 2.3.1
  flutter_local_notifications: 8.0.0
  flutter_local_notifications_linux: 0.2.0+1
  uuid: 3.0.4
  flutter_sound: 8.1.4 # TODO remove later
  record: 3.0.0
  percent_indicator: 3.0.1
  package_info: 2.0.2
  package_info_plus: 1.0.3
  package_info_plus_windows: 1.0.3
  sms_autofill: 2.1.2
  sorted_list: 1.0.0
  scrollable_positioned_list: 0.1.10
  share: 2.0.4
  fluttertoast: ^8.0.8
  firebase_messaging: 10.0.1
  firebase_core: 1.2.1
  flutter_swiper: 1.1.6
  desktop_drop: 0.1.0
  ## mockito: 5.0.10 # Great Library for Mocking in Tests
  test:
  badges: 2.0.1
  modal_bottom_sheet: 2.0.0
  receive_sharing_intent: 1.4.5
  qr_flutter: 4.0.0
  flutter_parsed_text: 1.2.5
  msix: 2.1.3
  device_info: 2.0.2
  hive: 2.0.4
  flutter_blurhash: 0.6.0
  hive_flutter: 1.1.0
  marquee: 2.2.0
  metadata_fetch: 0.4.1
  flutter_webrtc: ^0.6.10+hotfix.1
  sdp_transform: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  hive_generator: ^1.1.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/a.flr
    - assets/ic_launcher/res/mipmap-xxxhdpi/ic_launcher.png
    - assets/ic_launcher/web_hi_res_512.png
    - assets/audios/sound_in.wav
    - assets/audios/sound_out.wav
    - assets/audios/incoming-msg.mp3
    - lib/lang/fa.json
    - lib/lang/en.json
    - assets/backgrounds/
    - assets/animations/done.json
    - assets/animations/loading.json
    - assets/animations/error.json
    - assets/animations/audio_wave.json
    - assets/emoji/
    - android/app/src/main/res/raw/
    - assets/audios/beep_ringing_calling_sound.mp3
    - assets/animations/accept_call.json
    - assets/audios/Busy-sound.mp3

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: NotoColorEmoji
      fonts:
        - asset: assets/fonts/NotoColorEmoji.ttf
    - family: Vazir
      fonts:
        - asset: assets/fonts/vazir/Vazir-Variable.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
#analyzer:
#  strong-mode: true
#  language:
#    enableSuperMixins: true
