# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

# build appbundle --target-platform android-arm,android-arm64,android-x64

name: deliver
description: Messenger App

# PUBSPEC VERSION
version: 2.1.0  #if change the version , is necessary to change VERSION  in constants.dart

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  android_intent_plus: 3.1.1+1
  audioplayers:
    git:
      ref: b661c7d4c6f28b08773eba5cdfcc9ecabd61c151
      url: https://github.com/deliveriais/audioplayers
      path: packages/audioplayers
  badges: 2.0.3
  camera: 0.10.0+1
  card_swiper: 2.0.4
  chewie: 1.3.5
  circular_countdown_timer: 0.2.2
  clock: 1.1.1
  collection: 1.16.0
  connectivity_plus: 2.3.6+1
  connectycube_flutter_call_kit:
    git:
      ref: fbfe3a539c70fe2f9fed19f6a42497bbe8de1894
      url: https://github.com/deliveriais/connectycube_flutter_call_kit
  contacts_service: 0.6.3
  custom_image_crop: 0.0.4
  date_time_format: 2.0.1
  dcache: 0.4.0
  deliver_public_protocol:
    git:
      ref: tags/v1.12.13-rc.29
      url: https://github.com/deliver-iais/pub-dart-artifactory
  desktop_drop: 0.3.3
  desktop_lifecycle: 0.1.0
  desktop_window:
    git:
      ref: main
      url: https://github.com/deliveriais/desktop_window
  device_info: 2.0.3
  dio: 4.0.6
  expandable: 5.0.1
  feature_discovery:
    git:
      ref: 319d1fe74fcee87eef427a6136639b3bf2537a89
      url: https://github.com/deliveriais/feature_discovery
  file_picker: 4.6.1
  file_selector: 0.8.4+3
  file_selector_linux: 0.0.2+1
  firebase_analytics: 9.3.4
  firebase_core: 1.22.0
  firebase_messaging: 13.0.1
  fixnum: 1.0.1
  flare_flutter: 3.0.2
  flutter:
    sdk: flutter
  flutter_audio_waveforms: 1.2.1+6
  flutter_blurhash: 0.7.0
  flutter_dropzone: 3.0.5
  flutter_foreground_task: 3.8.2
  flutter_image_compress: 1.1.1
  flutter_keyboard_visibility: 5.3.0
  flutter_local_notifications: 10.0.0-dev.20
  flutter_localizations:
    sdk: flutter
  flutter_map: 3.0.0
  flutter_webrtc: 0.9.6
  fluttertoast: 8.0.9
  font_awesome_flutter: 10.1.0
  fuzzy: 0.4.0-nullsafety.0
  geolocator: 9.0.1
  get_it: 7.2.0
  google_fonts: 3.0.1
  great_list_view:
    git:
      ref: master
      url: https://github.com/deliveriais/great_list_view
  grpc:
    git:
      ref: master
      url: https://github.com/deliveriais/grpc-dart
  hive: 2.2.3
  hive_flutter: 1.1.0
  hovering: 1.0.4
  http: 0.13.5
  http_parser: 4.0.1
  image_compression_flutter: 1.0.2
  image_cropper: 3.0.0
  image_size_getter: 2.1.2
  intl: 0.17.0
  js: 0.6.4
  just_audio: 0.9.28
  just_audio_windows:
    git:
      path: just_audio_windows
      ref: 413f05fd2b9e063f4b7fa2903031a174ce3b6b0b
      url: https://github.com/bdlukaa/just_audio
  jwt_decoder: 2.0.1
  latlong2: 0.8.1
  logger: 1.1.0
  lottie: 1.4.1
  marquee: 2.2.3
  material_color_utilities: 0.1.5
  map_launcher: ^2.4.0
  maps_launcher: ^2.0.1
  meta: 1.8.0
  metadata_fetch: 0.4.1
  mime_type: 1.0.0
  mobile_scanner: 2.0.0
  modal_bottom_sheet: 2.1.0
  open_file: 3.2.1
  pasteboard: 0.2.0
  path: 1.8.2
  path_provider: 2.0.11
  path_provider_android: 2.0.15
  patterns_canvas: 0.4.0 # UPDATABLE in FLUTTER 3
  percent_indicator: 4.2.2
  permission_handler: 9.2.0
  persian_datetime_picker: 2.5.0
  photo_manager: 2.2.1
  photo_view: 0.14.0
  platform_detect: 2.0.7
  process_run: 0.12.3+2
  qr_flutter: 4.0.0
  random_string: 2.3.1
  receive_sharing_intent: 1.4.5
  record:
    git:
      path: record
      ref: d0d1ce44ed67ba92b313405ce4f8b50bc4980bda
      url: https://github.com/deliveriais/record
  rxdart: 0.27.5
  screenshot: 1.2.3
  scrollable_positioned_list: 0.3.2
  sdp_transform: 0.3.2
  sensors_plus: 1.3.4+1
  service_worker: 0.2.4
  share: 2.0.4
  shimmer: 2.0.0
  simple_animations: 4.1.0
  sms_autofill: 2.2.0
  synchronized: 3.0.0+2
  tuple: 2.0.0
  universal_html: 2.0.8
  url_launcher: 6.1.5
  uuid: 3.0.6
  vibration: 1.7.6
  video_player: 2.4.7
  win_toast:
    git:
      path: packages/win_toast
      ref: 5357c2a594a20534bf759eb28c86f8669d3914f3
      url: https://github.com/deliveriais/flutter-plugins
  window_size:
    git:
      path: plugins/window_size
      ref: 5c51870ced62a00e809ba4b81a846a052d241c9f
      url: https://github.com/google/flutter-desktop-embedding
  location: ^4.4.0



dev_dependencies:
  build_runner: 2.2.0
  dependency_validator: 3.2.2  # flutter pub run dependency_validator
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter
  hive_generator: 1.1.3

  integration_test:
    sdk: flutter
  mockito: 5.3.0
  msix: 3.6.3



# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - android/app/src/main/res/raw/
    - assets/animations/accept_call.json
    - assets/animations/arrow.json
    - assets/animations/audio_wave.tgs
    - assets/animations/clock.json
    - assets/animations/lock.json
    - assets/animations/done.tgs
    - assets/animations/file-save.json
    - assets/animations/not-found.tgs
    - assets/animations/touch.zip
    - assets/animations/unlock.tgs
    - assets/audios/beep_sound.mp3
    - assets/audios/busy_sound.mp3
    - assets/audios/incoming_call.mp3
    - assets/audios/incoming_msg.mp3
    - assets/audios/sound_in.wav
    - assets/audios/sound_out.wav
    - assets/backgrounds/
    - assets/emoji/
    - assets/ic_launcher/res/mipmap-xxxhdpi/ic_launcher.png
    - assets/images/a.flr
    - assets/images/logo.png
    - assets/images/no-profile-pic.png
    - assets/images/wave.png
    - lib/lang/en.json
    - lib/lang/fa.json
    - assets/animations/end_of_call.json
    - assets/audios/end_call.mp3
    - assets/animations/new_version.zip
    - assets/animations/out_of_date.zip
    - assets/animations/call_permission.tgs
    - assets/animations/qr.zip
    - assets/duck_animation/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts: [ ]
