name: deliver_flutter
description: Messenger App

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  carousel_slider: 2.2.1
  dots_indicator: 1.2.0

  flare_flutter: 2.0.6 # Animation Viewer Library
  date_time_format: 1.0.0+4

  emojis: 0.9.3
  permissions_plugin: 1.1.4 # ANDROID ONLY SUPPORTED

  ext_storage: 1.0.3
  path_provider: 1.6.24
  path:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: 1.0.0

  fimber: 0.4.4 # Logger Library (DELETE-ABLE CANDIDATE)
  get_it: 4.0.4 # Dependency Injector Library
  rxdart: 0.24.1 # State Management Library & Advanced Streaming Library
  auto_route: 0.6.7 # Routing Library

  window_size: # (DESKTOP ONLY) Setting min and max window size in desktop
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: 0efb6b14a802a01b5432b2a2ee97c7f4821f2ab2

  file_chooser:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/file_chooser
      ref: 0efb6b14a802a01b5432b2a2ee97c7f4821f2ab2
  dio: 3.0.10 # HTTP Invoker Library
  jwt_decoder: 1.0.1
  deliver_public_protocol: # DELIVER PROJECT PUBLIC GRPC PROTOCOL
    git:
      url: https://gitlab.iais.co/deliver/protocol/pub-dart-artifactory.git
      ref: tags/v1.4.7
  grpc: 2.2.0 # (WEB NOT SUPPORTED BI-Directional Streaming)
  protobuf: 1.0.1 # (WEB NOT SUPPORTED BI-Directional Streaming)
  storage_path: 0.2.0 # (DESKTOP NOT SUPPORTED, BACKUP PLAN: FILE CHOOSER)
  image_picker: 0.6.7+7 # (DESKTOP NOT SUPPORTED, BACKUP PLAN: ?) -> CAMERA
  image_cropper: 1.3.1 # (DESKTOP NOT SUPPORTED, NO BACKUP PLAN)
  vibration: 1.4.0 # (DESKTOP NOT SUPPORTED, NO BACKUP NEEDED)
  dcache: 0.3.0

  sqflite_common_ffi: 1.1.0+1

  video_player: ^0.10.11+2
  open_file: ^3.0.1
  fluttertoast: ^3.1.3
  flutter_native_image: ^0.0.5
  flutter_uploader: ^1.2.0
  contacts_service: ^0.4.6
  random_string: 2.1.0
  flutter_local_notifications: ^1.4.4+1
  audioplayers: ^0.15.1
  audio_service: ^0.11.2
  flutter_timer: 0.0.6
  uuid: 2.2.0
  audio_recorder: 1.0.2
  percent_indicator: 2.1.8
  step_progress_indicator: ^0.2.3+6
  cached_network_image: ^2.0.0
  flutter_swiper: ^1.0.0
  swipedetector: ^1.2.0
  moor: 3.3.1 # Multi-Platform ORM
  sqlite3_flutter_libs: 0.2.0 # Moor Needed Library
  sms_autofill: 1.2.5
  firebase_messaging: 7.0.0
  firebase_core: 0.5.0
  mockito: 4.1.1 # Great Library for Mocking in Tests
  data_connection_checker: ^0.3.4
  scrollable_positioned_list: 0.1.8
  test:


  receive_sharing_intent: 1.4.1

  flutter_icons: 1.1.0

  device_info: 0.4.2+8



  path_provider_fde:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/flutter_plugins/path_provider_fde
      ref: 66e4b05


dev_dependencies:
  flutter_test:
    sdk: flutter

  moor_generator: ^3.3.1
  build_runner:
  auto_route_generator: ^0.6.7


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/a.flr
    - assets/ic_launcher/res/mipmap-xxxhdpi/ic_launcher.png
    - assets/audios/r.mp3
    - lib/lang/fa.json
    - lib/lang/en.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Vazir
      fonts:
        - asset: assets/fonts/vazir/Vazir.ttf
        - asset: assets/fonts/vazir/Vazir-Bold.ttf
        - asset: assets/fonts/vazir/Vazir-Light.ttf
        - asset: assets/fonts/vazir/Vazir-Medium.ttf
        - asset: assets/fonts/vazir/Vazir-Thin.ttf
          weight: 700
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
