const SHARED_DAO_SHOW_CONTACT_DIALOG = "SHARED_DAO_SHOW_CONTACT_DIALOG";
const SHARED_DAO_THEME = "SHARED_DAO_THEME";
const SHARED_DAO_LANGUAGE = "SHARED_DAO_LANGUAGE";
const SHARED_DAO_FIREBASE_SETTING_IS_SET = "SHARED_DAO_FIREBASE_SETTING_IS_SET";
const SHARED_DAO_CURRENT_USER_UID = "SHARED_DAO_CURRENT_USER_UID";
const SHARED_DAO_NOTIFICATION = "SHARED_DAO_NOTIFICATION";
const SHARED_DAO_PHONE_NUMBER = "SHARED_DAO_PHONE_NUMBER";
const SHARED_DAO_DESCRIPTION = "SHARED_DAO_DESCRIPTION";
const SHARED_DAO_EMAIL = "SHARED_DAO_EMAIL";
const SHARED_DAO_PASSWORD = "SHARED_DAO_PASSWORD";
const SHARED_DAO_FIRST_NAME = "SHARED_DAO_FIRST_NAME";
const SHARED_DAO_LAST_NAME = "SHARED_DAO_LAST_NAME";
const SHARED_DAO_USERNAME = "SHARED_DAO_USERNAME";
const SHARED_DAO_ACCESS_TOKEN_KEY = "SHARED_DAO_ACCESS_TOKEN_KEY";
const SHARED_DAO_REFRESH_TOKEN_KEY = "SHARED_DAO_REFRESH_TOKEN_KEY";

const ONLINE_TIME = 60000;

const AVATAR_TRACK_ID = 1;
const LAST_ACTIVITY_TRACK_ID = 2;
const CONTACT_TRACK_ID = 3;
const UID_ID_NAME_TRACK_ID = 4;
const SEEN_TRACK_ID = 5;
const FILE_INFO_TRACK_ID = 6;
const MUC_TRACK_ID = 7;