// Mocks generated by Mockito 5.1.0 from annotations
// in deliver/test/helper/test_helper.dart.
// Do not manually edit this file.

import 'dart:async' as _i13;
import 'dart:io' as _i25;

import 'package:deliver/box/avatar.dart' as _i21;
import 'package:deliver/box/dao/block_dao.dart' as _i41;
import 'package:deliver/box/dao/last_activity_dao.dart' as _i37;
import 'package:deliver/box/dao/message_dao.dart' as _i12;
import 'package:deliver/box/dao/room_dao.dart' as _i16;
import 'package:deliver/box/dao/seen_dao.dart' as _i31;
import 'package:deliver/box/dao/shared_dao.dart' as _i39;
import 'package:deliver/box/livelocation.dart' as _i29;
import 'package:deliver/box/message.dart' as _i14;
import 'package:deliver/box/pending_message.dart' as _i15;
import 'package:deliver/box/room.dart' as _i17;
import 'package:deliver/box/seen.dart' as _i2;
import 'package:deliver/repository/authRepo.dart' as _i20;
import 'package:deliver/repository/avatarRepo.dart' as _i40;
import 'package:deliver/repository/fileRepo.dart' as _i24;
import 'package:deliver/repository/liveLocationRepo.dart' as _i28;
import 'package:deliver/repository/roomRepo.dart' as _i18;
import 'package:deliver/services/core_services.dart' as _i34;
import 'package:deliver/services/file_service.dart' as _i27;
import 'package:deliver/services/muc_services.dart' as _i32;
import 'package:deliver_public_protocol/pub/v1/channel.pbgrpc.dart' as _i8;
import 'package:deliver_public_protocol/pub/v1/group.pbgrpc.dart' as _i7;
import 'package:deliver_public_protocol/pub/v1/live_location.pbgrpc.dart'
    as _i6;
import 'package:deliver_public_protocol/pub/v1/models/activity.pb.dart' as _i19;
import 'package:deliver_public_protocol/pub/v1/models/file.pb.dart' as _i26;
import 'package:deliver_public_protocol/pub/v1/models/location.pb.dart' as _i30;
import 'package:deliver_public_protocol/pub/v1/models/message.pb.dart' as _i35;
import 'package:deliver_public_protocol/pub/v1/models/muc.pb.dart' as _i33;
import 'package:deliver_public_protocol/pub/v1/models/phone.pb.dart' as _i22;
import 'package:deliver_public_protocol/pub/v1/models/platform.pb.dart' as _i4;
import 'package:deliver_public_protocol/pub/v1/models/seen.pb.dart' as _i36;
import 'package:deliver_public_protocol/pub/v1/models/session.pb.dart' as _i23;
import 'package:deliver_public_protocol/pub/v1/models/uid.pb.dart' as _i3;
import 'package:deliver_public_protocol/pub/v1/profile.pbgrpc.dart' as _i5;
import 'package:deliver_public_protocol/pub/v1/query.pbgrpc.dart' as _i38;
import 'package:grpc/grpc.dart' as _i10;
import 'package:logger/logger.dart' as _i11;
import 'package:mockito/mockito.dart' as _i1;
import 'package:rxdart/rxdart.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeSeen_0 extends _i1.Fake implements _i2.Seen {}

class _FakeUid_1 extends _i1.Fake implements _i3.Uid {}

class _FakePlatform_2 extends _i1.Fake implements _i4.Platform {}

class _FakeAccessTokenRes_3 extends _i1.Fake implements _i5.AccessTokenRes {}

class _FakeCreateLiveLocationRes_4 extends _i1.Fake
    implements _i6.CreateLiveLocationRes {}

class _FakeGroupServiceClient_5 extends _i1.Fake
    implements _i7.GroupServiceClient {}

class _FakeChannelServiceClient_6 extends _i1.Fake
    implements _i8.ChannelServiceClient {}

class _FakeGetMembersRes_7 extends _i1.Fake implements _i7.GetMembersRes {}

class _FakeBehaviorSubject_8<T> extends _i1.Fake
    implements _i9.BehaviorSubject<T> {}

class _FakeResponseFuture_9<R> extends _i1.Fake
    implements _i10.ResponseFuture<R> {}

class _FakeClientCall_10<Q, R> extends _i1.Fake
    implements _i10.ClientCall<Q, R> {}

class _FakeResponseStream_11<R> extends _i1.Fake
    implements _i10.ResponseStream<R> {}

/// A class which mocks [Logger].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogger extends _i1.Mock implements _i11.Logger {
  @override
  void v(dynamic message, [dynamic error, StackTrace? stackTrace]) =>
      super.noSuchMethod(Invocation.method(#v, [message, error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  void d(dynamic message, [dynamic error, StackTrace? stackTrace]) =>
      super.noSuchMethod(Invocation.method(#d, [message, error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  void i(dynamic message, [dynamic error, StackTrace? stackTrace]) =>
      super.noSuchMethod(Invocation.method(#i, [message, error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  void w(dynamic message, [dynamic error, StackTrace? stackTrace]) =>
      super.noSuchMethod(Invocation.method(#w, [message, error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  void e(dynamic message, [dynamic error, StackTrace? stackTrace]) =>
      super.noSuchMethod(Invocation.method(#e, [message, error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  void wtf(dynamic message, [dynamic error, StackTrace? stackTrace]) =>
      super.noSuchMethod(Invocation.method(#wtf, [message, error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  void log(_i11.Level? level, dynamic message,
          [dynamic error, StackTrace? stackTrace]) =>
      super.noSuchMethod(
          Invocation.method(#log, [level, message, error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  void close() => super.noSuchMethod(Invocation.method(#close, []),
      returnValueForMissingStub: null);
}

/// A class which mocks [MessageDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockMessageDao extends _i1.Mock implements _i12.MessageDao {
  @override
  _i13.Future<void> saveMessage(_i14.Message? message) => (super.noSuchMethod(
      Invocation.method(#saveMessage, [message]),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i13.Future<void>);
  @override
  _i13.Future<void> deleteMessage(_i14.Message? message) => (super.noSuchMethod(
      Invocation.method(#deleteMessage, [message]),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i13.Future<void>);
  @override
  _i13.Future<_i14.Message?> getMessage(String? roomUid, int? id) =>
      (super.noSuchMethod(Invocation.method(#getMessage, [roomUid, id]),
              returnValue: Future<_i14.Message?>.value())
          as _i13.Future<_i14.Message?>);
  @override
  _i13.Future<List<_i14.Message?>>? getMessagePage(String? roomUid, int? page,
          {int? pageSize = 16}) =>
      (super.noSuchMethod(Invocation.method(
              #getMessagePage, [roomUid, page], {#pageSize: pageSize}))
          as _i13.Future<List<_i14.Message?>>?);
  @override
  _i13.Future<List<_i15.PendingMessage>> getPendingMessages(String? roomUid) =>
      (super.noSuchMethod(Invocation.method(#getPendingMessages, [roomUid]),
              returnValue: Future<List<_i15.PendingMessage>>.value(
                  <_i15.PendingMessage>[]))
          as _i13.Future<List<_i15.PendingMessage>>);
  @override
  _i13.Stream<List<_i15.PendingMessage>> watchPendingMessages(
          String? roomUid) =>
      (super.noSuchMethod(Invocation.method(#watchPendingMessages, [roomUid]),
              returnValue: Stream<List<_i15.PendingMessage>>.empty())
          as _i13.Stream<List<_i15.PendingMessage>>);
  @override
  _i13.Future<_i15.PendingMessage?> getPendingMessage(String? packetId) =>
      (super.noSuchMethod(Invocation.method(#getPendingMessage, [packetId]),
              returnValue: Future<_i15.PendingMessage?>.value())
          as _i13.Future<_i15.PendingMessage?>);
  @override
  _i13.Stream<_i15.PendingMessage?> watchPendingMessage(String? packetId) =>
      (super.noSuchMethod(Invocation.method(#watchPendingMessage, [packetId]),
              returnValue: Stream<_i15.PendingMessage?>.empty())
          as _i13.Stream<_i15.PendingMessage?>);
  @override
  _i13.Future<List<_i15.PendingMessage>> getAllPendingMessages() =>
      (super.noSuchMethod(Invocation.method(#getAllPendingMessages, []),
              returnValue: Future<List<_i15.PendingMessage>>.value(
                  <_i15.PendingMessage>[]))
          as _i13.Future<List<_i15.PendingMessage>>);
  @override
  _i13.Future<void> deletePendingMessage(String? packetId) =>
      (super.noSuchMethod(Invocation.method(#deletePendingMessage, [packetId]),
              returnValue: Future<void>.value(),
              returnValueForMissingStub: Future<void>.value())
          as _i13.Future<void>);
  @override
  _i13.Future<void> savePendingMessage(_i15.PendingMessage? pm) =>
      (super.noSuchMethod(Invocation.method(#savePendingMessage, [pm]),
              returnValue: Future<void>.value(),
              returnValueForMissingStub: Future<void>.value())
          as _i13.Future<void>);
}

/// A class which mocks [RoomDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockRoomDao extends _i1.Mock implements _i16.RoomDao {
  @override
  _i13.Future<void> updateRoom(_i17.Room? room) => (super.noSuchMethod(
      Invocation.method(#updateRoom, [room]),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i13.Future<void>);
  @override
  _i13.Future<void> deleteRoom(_i17.Room? room) => (super.noSuchMethod(
      Invocation.method(#deleteRoom, [room]),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i13.Future<void>);
  @override
  _i13.Future<List<_i17.Room>> getAllRooms() =>
      (super.noSuchMethod(Invocation.method(#getAllRooms, []),
              returnValue: Future<List<_i17.Room>>.value(<_i17.Room>[]))
          as _i13.Future<List<_i17.Room>>);
  @override
  _i13.Stream<List<_i17.Room>> watchAllRooms() =>
      (super.noSuchMethod(Invocation.method(#watchAllRooms, []),
              returnValue: Stream<List<_i17.Room>>.empty())
          as _i13.Stream<List<_i17.Room>>);
  @override
  _i13.Future<_i17.Room?> getRoom(String? roomUid) =>
      (super.noSuchMethod(Invocation.method(#getRoom, [roomUid]),
          returnValue: Future<_i17.Room?>.value()) as _i13.Future<_i17.Room?>);
  @override
  _i13.Stream<_i17.Room> watchRoom(String? roomUid) =>
      (super.noSuchMethod(Invocation.method(#watchRoom, [roomUid]),
          returnValue: Stream<_i17.Room>.empty()) as _i13.Stream<_i17.Room>);
  @override
  _i13.Future<List<_i17.Room>> getAllGroups() =>
      (super.noSuchMethod(Invocation.method(#getAllGroups, []),
              returnValue: Future<List<_i17.Room>>.value(<_i17.Room>[]))
          as _i13.Future<List<_i17.Room>>);
}

/// A class which mocks [RoomRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockRoomRepo extends _i1.Mock implements _i18.RoomRepo {
  @override
  Map<String, _i9.BehaviorSubject<_i19.Activity>> get activityObject =>
      (super.noSuchMethod(Invocation.getter(#activityObject),
              returnValue: <String, _i9.BehaviorSubject<_i19.Activity>>{})
          as Map<String, _i9.BehaviorSubject<_i19.Activity>>);
  @override
  dynamic insertRoom(String? uid) =>
      super.noSuchMethod(Invocation.method(#insertRoom, [uid]));
  @override
  dynamic updateRoom(_i17.Room? room) =>
      super.noSuchMethod(Invocation.method(#updateRoom, [room]));
  @override
  _i13.Future<String> getSlangName(_i3.Uid? uid) =>
      (super.noSuchMethod(Invocation.method(#getSlangName, [uid]),
          returnValue: Future<String>.value('')) as _i13.Future<String>);
  @override
  _i13.Future<bool> isVerified(_i3.Uid? uid) =>
      (super.noSuchMethod(Invocation.method(#isVerified, [uid]),
          returnValue: Future<bool>.value(false)) as _i13.Future<bool>);
  @override
  String? fastForwardName(_i3.Uid? uid) =>
      (super.noSuchMethod(Invocation.method(#fastForwardName, [uid]))
          as String?);
  @override
  _i13.Future<String> getName(_i3.Uid? uid) =>
      (super.noSuchMethod(Invocation.method(#getName, [uid]),
          returnValue: Future<String>.value('')) as _i13.Future<String>);
  @override
  _i13.Future<String?>? getId(_i3.Uid? uid) =>
      (super.noSuchMethod(Invocation.method(#getId, [uid]))
          as _i13.Future<String?>?);
  @override
  _i13.Future<bool> deleteRoom(_i3.Uid? roomUid) =>
      (super.noSuchMethod(Invocation.method(#deleteRoom, [roomUid]),
          returnValue: Future<bool>.value(false)) as _i13.Future<bool>);
  @override
  _i13.Future<String?> getIdByUid(_i3.Uid? uid) =>
      (super.noSuchMethod(Invocation.method(#getIdByUid, [uid]),
          returnValue: Future<String?>.value()) as _i13.Future<String?>);
  @override
  void updateActivity(_i19.Activity? activity) =>
      super.noSuchMethod(Invocation.method(#updateActivity, [activity]),
          returnValueForMissingStub: null);
  @override
  void initActivity(String? roomId) =>
      super.noSuchMethod(Invocation.method(#initActivity, [roomId]),
          returnValueForMissingStub: null);
  @override
  dynamic updateRoomName(_i3.Uid? uid, String? name) =>
      super.noSuchMethod(Invocation.method(#updateRoomName, [uid, name]));
  @override
  _i13.Future<bool> isRoomHaveACustomNotification(String? uid) => (super
      .noSuchMethod(Invocation.method(#isRoomHaveACustomNotification, [uid]),
          returnValue: Future<bool>.value(false)) as _i13.Future<bool>);
  @override
  dynamic setRoomCustomNotification(String? uid, String? path) => super
      .noSuchMethod(Invocation.method(#setRoomCustomNotification, [uid, path]));
  @override
  _i13.Future<String?> getRoomCustomNotification(String? uid) =>
      (super.noSuchMethod(Invocation.method(#getRoomCustomNotification, [uid]),
          returnValue: Future<String?>.value()) as _i13.Future<String?>);
  @override
  _i13.Future<bool> isRoomMuted(String? uid) =>
      (super.noSuchMethod(Invocation.method(#isRoomMuted, [uid]),
          returnValue: Future<bool>.value(false)) as _i13.Future<bool>);
  @override
  _i13.Stream<bool> watchIsRoomMuted(String? uid) =>
      (super.noSuchMethod(Invocation.method(#watchIsRoomMuted, [uid]),
          returnValue: Stream<bool>.empty()) as _i13.Stream<bool>);
  @override
  void mute(String? uid) => super.noSuchMethod(Invocation.method(#mute, [uid]),
      returnValueForMissingStub: null);
  @override
  void unmute(String? uid) =>
      super.noSuchMethod(Invocation.method(#unmute, [uid]),
          returnValueForMissingStub: null);
  @override
  _i13.Future<bool> isRoomBlocked(String? uid) =>
      (super.noSuchMethod(Invocation.method(#isRoomBlocked, [uid]),
          returnValue: Future<bool>.value(false)) as _i13.Future<bool>);
  @override
  _i13.Stream<bool?> watchIsRoomBlocked(String? uid) =>
      (super.noSuchMethod(Invocation.method(#watchIsRoomBlocked, [uid]),
          returnValue: Stream<bool?>.empty()) as _i13.Stream<bool?>);
  @override
  _i13.Stream<List<_i17.Room>> watchAllRooms() =>
      (super.noSuchMethod(Invocation.method(#watchAllRooms, []),
              returnValue: Stream<List<_i17.Room>>.empty())
          as _i13.Stream<List<_i17.Room>>);
  @override
  _i13.Stream<_i17.Room> watchRoom(String? roomUid) =>
      (super.noSuchMethod(Invocation.method(#watchRoom, [roomUid]),
          returnValue: Stream<_i17.Room>.empty()) as _i13.Stream<_i17.Room>);
  @override
  _i13.Future<_i17.Room?> getRoom(String? roomUid) =>
      (super.noSuchMethod(Invocation.method(#getRoom, [roomUid]),
          returnValue: Future<_i17.Room?>.value()) as _i13.Future<_i17.Room?>);
  @override
  _i13.Future<void> resetMention(String? roomUid) => (super.noSuchMethod(
      Invocation.method(#resetMention, [roomUid]),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i13.Future<void>);
  @override
  _i13.Future<void> createRoomIfNotExist(String? roomUid) =>
      (super.noSuchMethod(Invocation.method(#createRoomIfNotExist, [roomUid]),
              returnValue: Future<void>.value(),
              returnValueForMissingStub: Future<void>.value())
          as _i13.Future<void>);
  @override
  _i13.Stream<_i2.Seen> watchMySeen(String? roomUid) =>
      (super.noSuchMethod(Invocation.method(#watchMySeen, [roomUid]),
          returnValue: Stream<_i2.Seen>.empty()) as _i13.Stream<_i2.Seen>);
  @override
  _i13.Future<_i2.Seen> getMySeen(String? roomUid) =>
      (super.noSuchMethod(Invocation.method(#getMySeen, [roomUid]),
              returnValue: Future<_i2.Seen>.value(_FakeSeen_0()))
          as _i13.Future<_i2.Seen>);
  @override
  _i13.Future<_i2.Seen?> getOthersSeen(String? roomUid) =>
      (super.noSuchMethod(Invocation.method(#getOthersSeen, [roomUid]),
          returnValue: Future<_i2.Seen?>.value()) as _i13.Future<_i2.Seen?>);
  @override
  _i13.Future<void> saveMySeen(_i2.Seen? seen) => (super.noSuchMethod(
      Invocation.method(#saveMySeen, [seen]),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i13.Future<void>);
  @override
  void block(String? uid, {bool? block}) =>
      super.noSuchMethod(Invocation.method(#block, [uid], {#block: block}),
          returnValueForMissingStub: null);
  @override
  _i13.Future<List<_i3.Uid>> getAllRooms() =>
      (super.noSuchMethod(Invocation.method(#getAllRooms, []),
              returnValue: Future<List<_i3.Uid>>.value(<_i3.Uid>[]))
          as _i13.Future<List<_i3.Uid>>);
  @override
  _i13.Future<List<_i3.Uid>> searchInRoomAndContacts(String? text) =>
      (super.noSuchMethod(Invocation.method(#searchInRoomAndContacts, [text]),
              returnValue: Future<List<_i3.Uid>>.value(<_i3.Uid>[]))
          as _i13.Future<List<_i3.Uid>>);
  @override
  _i13.Future<String> getUidById(String? id) =>
      (super.noSuchMethod(Invocation.method(#getUidById, [id]),
          returnValue: Future<String>.value('')) as _i13.Future<String>);
  @override
  _i13.Future<_i3.Uid> fetchUidById(String? username) =>
      (super.noSuchMethod(Invocation.method(#fetchUidById, [username]),
              returnValue: Future<_i3.Uid>.value(_FakeUid_1()))
          as _i13.Future<_i3.Uid>);
  @override
  void reportRoom(_i3.Uid? roomUid) =>
      super.noSuchMethod(Invocation.method(#reportRoom, [roomUid]),
          returnValueForMissingStub: null);
  @override
  _i13.Future<List<_i17.Room>> getAllGroups() =>
      (super.noSuchMethod(Invocation.method(#getAllGroups, []),
              returnValue: Future<List<_i17.Room>>.value(<_i17.Room>[]))
          as _i13.Future<List<_i17.Room>>);
  @override
  void updateRoomDraft(String? roomUid, String? draft) =>
      super.noSuchMethod(Invocation.method(#updateRoomDraft, [roomUid, draft]),
          returnValueForMissingStub: null);
  @override
  _i13.Future<bool> isDeletedRoom(String? roomUid) =>
      (super.noSuchMethod(Invocation.method(#isDeletedRoom, [roomUid]),
          returnValue: Future<bool>.value(false)) as _i13.Future<bool>);
}

/// A class which mocks [AuthRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepo extends _i1.Mock implements _i20.AuthRepo {
  @override
  _i3.Uid get currentUserUid =>
      (super.noSuchMethod(Invocation.getter(#currentUserUid),
          returnValue: _FakeUid_1()) as _i3.Uid);
  @override
  set currentUserUid(_i3.Uid? _currentUserUid) =>
      super.noSuchMethod(Invocation.setter(#currentUserUid, _currentUserUid),
          returnValueForMissingStub: null);
  @override
  set avatar(_i21.Avatar? _avatar) =>
      super.noSuchMethod(Invocation.setter(#avatar, _avatar),
          returnValueForMissingStub: null);
  @override
  _i13.Future<bool> isTestUser() =>
      (super.noSuchMethod(Invocation.method(#isTestUser, []),
          returnValue: Future<bool>.value(false)) as _i13.Future<bool>);
  @override
  _i13.Future<void> init() => (super.noSuchMethod(Invocation.method(#init, []),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i13.Future<void>);
  @override
  _i13.Future<bool> getVerificationCode(_i22.PhoneNumber? p) =>
      (super.noSuchMethod(Invocation.method(#getVerificationCode, [p]),
          returnValue: Future<bool>.value(false)) as _i13.Future<bool>);
  @override
  _i13.Future<_i4.Platform> getPlatformDetails() =>
      (super.noSuchMethod(Invocation.method(#getPlatformDetails, []),
              returnValue: Future<_i4.Platform>.value(_FakePlatform_2()))
          as _i13.Future<_i4.Platform>);
  @override
  dynamic getPlatForm(_i4.Platform? platform) =>
      super.noSuchMethod(Invocation.method(#getPlatForm, [platform]));
  @override
  _i13.Future<String> getDeviceName() =>
      (super.noSuchMethod(Invocation.method(#getDeviceName, []),
          returnValue: Future<String>.value('')) as _i13.Future<String>);
  @override
  _i13.Future<_i5.AccessTokenRes> sendVerificationCode(String? code) =>
      (super.noSuchMethod(Invocation.method(#sendVerificationCode, [code]),
              returnValue:
                  Future<_i5.AccessTokenRes>.value(_FakeAccessTokenRes_3()))
          as _i13.Future<_i5.AccessTokenRes>);
  @override
  _i13.Future<_i5.AccessTokenRes> checkQrCodeToken(String? token) =>
      (super.noSuchMethod(Invocation.method(#checkQrCodeToken, [token]),
              returnValue:
                  Future<_i5.AccessTokenRes>.value(_FakeAccessTokenRes_3()))
          as _i13.Future<_i5.AccessTokenRes>);
  @override
  _i13.Future<String> getAccessToken() =>
      (super.noSuchMethod(Invocation.method(#getAccessToken, []),
          returnValue: Future<String>.value('')) as _i13.Future<String>);
  @override
  bool isLocalLockEnabled() =>
      (super.noSuchMethod(Invocation.method(#isLocalLockEnabled, []),
          returnValue: false) as bool);
  @override
  bool localPasswordIsCorrect(String? pass) =>
      (super.noSuchMethod(Invocation.method(#localPasswordIsCorrect, [pass]),
          returnValue: false) as bool);
  @override
  String getLocalPassword() =>
      (super.noSuchMethod(Invocation.method(#getLocalPassword, []),
          returnValue: '') as String);
  @override
  void setLocalPassword(String? pass) =>
      super.noSuchMethod(Invocation.method(#setLocalPassword, [pass]),
          returnValueForMissingStub: null);
  @override
  bool isLoggedIn() => (super.noSuchMethod(Invocation.method(#isLoggedIn, []),
      returnValue: false) as bool);
  @override
  bool isCurrentUser(String? uid) =>
      (super.noSuchMethod(Invocation.method(#isCurrentUser, [uid]),
          returnValue: false) as bool);
  @override
  bool isCurrentUserSender(_i14.Message? msg) =>
      (super.noSuchMethod(Invocation.method(#isCurrentUserSender, [msg]),
          returnValue: false) as bool);
  @override
  bool isCurrentSession(_i23.Session? session) =>
      (super.noSuchMethod(Invocation.method(#isCurrentSession, [session]),
          returnValue: false) as bool);
  @override
  _i13.Future<void> deleteTokens() => (super.noSuchMethod(
      Invocation.method(#deleteTokens, []),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i13.Future<void>);
}

/// A class which mocks [FileRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockFileRepo extends _i1.Mock implements _i24.FileRepo {
  @override
  Map<String, _i9.BehaviorSubject<int?>> get uploadFileStatusCode =>
      (super.noSuchMethod(Invocation.getter(#uploadFileStatusCode),
              returnValue: <String, _i9.BehaviorSubject<int?>>{})
          as Map<String, _i9.BehaviorSubject<int?>>);
  @override
  set uploadFileStatusCode(
          Map<String, _i9.BehaviorSubject<int?>>? _uploadFileStatusCode) =>
      super.noSuchMethod(
          Invocation.setter(#uploadFileStatusCode, _uploadFileStatusCode),
          returnValueForMissingStub: null);
  @override
  _i13.Future<void> cloneFileInLocalDirectory(
          _i25.File? file, String? uploadKey, String? name) =>
      (super.noSuchMethod(
              Invocation.method(
                  #cloneFileInLocalDirectory, [file, uploadKey, name]),
              returnValue: Future<void>.value(),
              returnValueForMissingStub: Future<void>.value())
          as _i13.Future<void>);
  @override
  _i13.Future<_i26.File?> uploadClonedFile(String? uploadKey, String? name,
          {Function? sendActivity}) =>
      (super.noSuchMethod(
          Invocation.method(#uploadClonedFile, [uploadKey, name],
              {#sendActivity: sendActivity}),
          returnValue: Future<_i26.File?>.value()) as _i13.Future<_i26.File?>);
  @override
  _i13.Future<bool> isExist(String? uuid, String? filename,
          {_i27.ThumbnailSize? thumbnailSize}) =>
      (super.noSuchMethod(
          Invocation.method(
              #isExist, [uuid, filename], {#thumbnailSize: thumbnailSize}),
          returnValue: Future<bool>.value(false)) as _i13.Future<bool>);
  @override
  dynamic saveDownloadedFile(String? url, String? filename) => super
      .noSuchMethod(Invocation.method(#saveDownloadedFile, [url, filename]));
  @override
  _i13.Future<String?> getFileIfExist(String? uuid, String? filename,
          {_i27.ThumbnailSize? thumbnailSize}) =>
      (super.noSuchMethod(
          Invocation.method(#getFileIfExist, [uuid, filename],
              {#thumbnailSize: thumbnailSize}),
          returnValue: Future<String?>.value()) as _i13.Future<String?>);
  @override
  _i13.Future<String?> getFile(String? uuid, String? filename,
          {_i27.ThumbnailSize? thumbnailSize, bool? intiProgressBar = true}) =>
      (super.noSuchMethod(
          Invocation.method(#getFile, [
            uuid,
            filename
          ], {
            #thumbnailSize: thumbnailSize,
            #intiProgressBar: intiProgressBar
          }),
          returnValue: Future<String?>.value()) as _i13.Future<String?>);
  @override
  void initUploadProgress(String? uploadId) =>
      super.noSuchMethod(Invocation.method(#initUploadProgress, [uploadId]),
          returnValueForMissingStub: null);
  @override
  void saveFileInDownloadDir(String? uuid, String? name, String? dir) =>
      super.noSuchMethod(
          Invocation.method(#saveFileInDownloadDir, [uuid, name, dir]),
          returnValueForMissingStub: null);
}

/// A class which mocks [LiveLocationRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockLiveLocationRepo extends _i1.Mock implements _i28.LiveLocationRepo {
  @override
  dynamic saveLiveLocation(_i29.LiveLocation? liveLocation) =>
      super.noSuchMethod(Invocation.method(#saveLiveLocation, [liveLocation]));
  @override
  _i13.Future<_i29.LiveLocation?> getLiveLocation(String? uuid) =>
      (super.noSuchMethod(Invocation.method(#getLiveLocation, [uuid]),
              returnValue: Future<_i29.LiveLocation?>.value())
          as _i13.Future<_i29.LiveLocation?>);
  @override
  _i13.Stream<_i29.LiveLocation?> watchLiveLocation(String? uuid) =>
      (super.noSuchMethod(Invocation.method(#watchLiveLocation, [uuid]),
              returnValue: Stream<_i29.LiveLocation?>.empty())
          as _i13.Stream<_i29.LiveLocation?>);
  @override
  _i13.Future<void> updateLiveLocation(_i30.LiveLocation? liveLocation) =>
      (super.noSuchMethod(
              Invocation.method(#updateLiveLocation, [liveLocation]),
              returnValue: Future<void>.value(),
              returnValueForMissingStub: Future<void>.value())
          as _i13.Future<void>);
  @override
  _i13.Future<_i6.CreateLiveLocationRes> createLiveLocation(
          _i3.Uid? roomUid, int? duration) =>
      (super.noSuchMethod(
              Invocation.method(#createLiveLocation, [roomUid, duration]),
              returnValue: Future<_i6.CreateLiveLocationRes>.value(
                  _FakeCreateLiveLocationRes_4()))
          as _i13.Future<_i6.CreateLiveLocationRes>);
  @override
  void sendLiveLocationAsStream(
          String? uuid, int? duration, _i30.Location? location) =>
      super.noSuchMethod(
          Invocation.method(
              #sendLiveLocationAsStream, [uuid, duration, location]),
          returnValueForMissingStub: null);
}

/// A class which mocks [SeenDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockSeenDao extends _i1.Mock implements _i31.SeenDao {
  @override
  _i13.Future<_i2.Seen?> getOthersSeen(String? uid) =>
      (super.noSuchMethod(Invocation.method(#getOthersSeen, [uid]),
          returnValue: Future<_i2.Seen?>.value()) as _i13.Future<_i2.Seen?>);
  @override
  _i13.Stream<_i2.Seen?> watchOthersSeen(String? uid) =>
      (super.noSuchMethod(Invocation.method(#watchOthersSeen, [uid]),
          returnValue: Stream<_i2.Seen?>.empty()) as _i13.Stream<_i2.Seen?>);
  @override
  _i13.Future<_i2.Seen> getMySeen(String? uid) =>
      (super.noSuchMethod(Invocation.method(#getMySeen, [uid]),
              returnValue: Future<_i2.Seen>.value(_FakeSeen_0()))
          as _i13.Future<_i2.Seen>);
  @override
  _i13.Stream<_i2.Seen> watchMySeen(String? uid) =>
      (super.noSuchMethod(Invocation.method(#watchMySeen, [uid]),
          returnValue: Stream<_i2.Seen>.empty()) as _i13.Stream<_i2.Seen>);
  @override
  _i13.Future<void> saveOthersSeen(_i2.Seen? seen) => (super.noSuchMethod(
      Invocation.method(#saveOthersSeen, [seen]),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i13.Future<void>);
  @override
  _i13.Future<void> saveMySeen(_i2.Seen? seen) => (super.noSuchMethod(
      Invocation.method(#saveMySeen, [seen]),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i13.Future<void>);
}

/// A class which mocks [MucServices].
///
/// See the documentation for Mockito's code generation for more information.
class MockMucServices extends _i1.Mock implements _i32.MucServices {
  @override
  _i7.GroupServiceClient get groupServices =>
      (super.noSuchMethod(Invocation.getter(#groupServices),
          returnValue: _FakeGroupServiceClient_5()) as _i7.GroupServiceClient);
  @override
  _i8.ChannelServiceClient get channelServices => (super.noSuchMethod(
      Invocation.getter(#channelServices),
      returnValue: _FakeChannelServiceClient_6()) as _i8.ChannelServiceClient);
  @override
  _i13.Future<_i3.Uid?> createNewGroup(String? groupName, String? info) =>
      (super.noSuchMethod(Invocation.method(#createNewGroup, [groupName, info]),
          returnValue: Future<_i3.Uid?>.value()) as _i13.Future<_i3.Uid?>);
  @override
  _i13.Future<bool> addGroupMembers(
          List<_i33.Member>? members, _i3.Uid? groupUid,
          {bool? retry = false}) =>
      (super.noSuchMethod(
          Invocation.method(
              #addGroupMembers, [members, groupUid], {#retry: retry}),
          returnValue: Future<bool>.value(false)) as _i13.Future<bool>);
  @override
  _i13.Future<_i7.GetGroupRes?> getGroup(_i3.Uid? groupUid) =>
      (super.noSuchMethod(Invocation.method(#getGroup, [groupUid]),
              returnValue: Future<_i7.GetGroupRes?>.value())
          as _i13.Future<_i7.GetGroupRes?>);
  @override
  _i13.Future<bool> removeGroup(_i3.Uid? groupUid) =>
      (super.noSuchMethod(Invocation.method(#removeGroup, [groupUid]),
          returnValue: Future<bool>.value(false)) as _i13.Future<bool>);
  @override
  _i13.Future<bool> changeGroupRole(_i33.Member? member, _i3.Uid? group) =>
      (super.noSuchMethod(Invocation.method(#changeGroupRole, [member, group]),
          returnValue: Future<bool>.value(false)) as _i13.Future<bool>);
  @override
  _i13.Future<_i7.GetMembersRes> getGroupMembers(
          _i3.Uid? groupUid, int? limit, int? pointer) =>
      (super.noSuchMethod(
              Invocation.method(#getGroupMembers, [groupUid, limit, pointer]),
              returnValue:
                  Future<_i7.GetMembersRes>.value(_FakeGetMembersRes_7()))
          as _i13.Future<_i7.GetMembersRes>);
  @override
  _i13.Future<bool> leaveGroup(_i3.Uid? groupUid) =>
      (super.noSuchMethod(Invocation.method(#leaveGroup, [groupUid]),
          returnValue: Future<bool>.value(false)) as _i13.Future<bool>);
  @override
  _i13.Future<bool> kickGroupMembers(
          List<_i33.Member>? members, _i3.Uid? groupUid) =>
      (super.noSuchMethod(
          Invocation.method(#kickGroupMembers, [members, groupUid]),
          returnValue: Future<bool>.value(false)) as _i13.Future<bool>);
  @override
  _i13.Future<bool> banGroupMember(_i33.Member? member, _i3.Uid? mucUid) =>
      (super.noSuchMethod(Invocation.method(#banGroupMember, [member, mucUid]),
          returnValue: Future<bool>.value(false)) as _i13.Future<bool>);
  @override
  _i13.Future<bool> unbanGroupMember(_i33.Member? member, _i3.Uid? mucUid) =>
      (super.noSuchMethod(
          Invocation.method(#unbanGroupMember, [member, mucUid]),
          returnValue: Future<bool>.value(false)) as _i13.Future<bool>);
  @override
  _i13.Future<bool> joinGroup(_i3.Uid? groupUid, String? token) =>
      (super.noSuchMethod(Invocation.method(#joinGroup, [groupUid, token]),
          returnValue: Future<bool>.value(false)) as _i13.Future<bool>);
  @override
  _i13.Future<bool> modifyGroup(_i7.GroupInfo? group, _i3.Uid? mucUid) =>
      (super.noSuchMethod(Invocation.method(#modifyGroup, [group, mucUid]),
          returnValue: Future<bool>.value(false)) as _i13.Future<bool>);
  @override
  _i13.Future<_i3.Uid?> createNewChannel(String? channelName,
          _i8.ChannelType? type, String? channelId, String? info,
          {bool? retry = true}) =>
      (super.noSuchMethod(
          Invocation.method(#createNewChannel,
              [channelName, type, channelId, info], {#retry: retry}),
          returnValue: Future<_i3.Uid?>.value()) as _i13.Future<_i3.Uid?>);
  @override
  _i13.Future<bool> addChannelMembers(
          List<_i33.Member>? members, _i3.Uid? mucUid) =>
      (super.noSuchMethod(
          Invocation.method(#addChannelMembers, [members, mucUid]),
          returnValue: Future<bool>.value(false)) as _i13.Future<bool>);
  @override
  _i13.Future<_i8.GetChannelRes?> getChannel(_i3.Uid? channelUid) =>
      (super.noSuchMethod(Invocation.method(#getChannel, [channelUid]),
              returnValue: Future<_i8.GetChannelRes?>.value())
          as _i13.Future<_i8.GetChannelRes?>);
  @override
  _i13.Future<bool> removeChannel(_i3.Uid? channelUid) =>
      (super.noSuchMethod(Invocation.method(#removeChannel, [channelUid]),
          returnValue: Future<bool>.value(false)) as _i13.Future<bool>);
  @override
  _i13.Future<bool> changeCahnnelRole(_i33.Member? member, _i3.Uid? channel) =>
      (super.noSuchMethod(
          Invocation.method(#changeCahnnelRole, [member, channel]),
          returnValue: Future<bool>.value(false)) as _i13.Future<bool>);
  @override
  _i13.Future<_i8.GetMembersRes?> getChannelMembers(
          _i3.Uid? channelUid, int? limit, int? pointer) =>
      (super.noSuchMethod(
          Invocation.method(#getChannelMembers, [channelUid, limit, pointer]),
          returnValue:
              Future<_i8.GetMembersRes?>.value()) as _i13
          .Future<_i8.GetMembersRes?>);
  @override
  _i13.Future<bool> leaveChannel(_i3.Uid? channelUid) =>
      (super.noSuchMethod(Invocation.method(#leaveChannel, [channelUid]),
          returnValue: Future<bool>.value(false)) as _i13.Future<bool>);
  @override
  _i13.Future<bool> kickChannelMembers(
          List<_i33.Member>? members, _i3.Uid? channelUid) =>
      (super.noSuchMethod(
          Invocation.method(#kickChannelMembers, [members, channelUid]),
          returnValue: Future<bool>.value(false)) as _i13.Future<bool>);
  @override
  _i13.Future<bool> banChannelMember(
          _i33.Member? member, _i3.Uid? channelUid) =>
      (super.noSuchMethod(
          Invocation.method(#banChannelMember, [member, channelUid]),
          returnValue: Future<bool>.value(false)) as _i13.Future<bool>);
  @override
  _i13.Future<bool> unbanChannelMember(
          _i33.Member? member, _i3.Uid? channelUid) =>
      (super.noSuchMethod(
          Invocation.method(#unbanChannelMember, [member, channelUid]),
          returnValue: Future<bool>.value(false)) as _i13.Future<bool>);
  @override
  _i13.Future<bool> joinChannel(_i3.Uid? channelUid, String? token) =>
      (super.noSuchMethod(Invocation.method(#joinChannel, [channelUid, token]),
          returnValue: Future<bool>.value(false)) as _i13.Future<bool>);
  @override
  _i13.Future<bool> modifyChannel(
          _i8.ChannelInfo? channelInfo, _i3.Uid? mucUid) =>
      (super.noSuchMethod(
          Invocation.method(#modifyChannel, [channelInfo, mucUid]),
          returnValue: Future<bool>.value(false)) as _i13.Future<bool>);
  @override
  _i13.Future<bool> pinMessage(_i14.Message? message) =>
      (super.noSuchMethod(Invocation.method(#pinMessage, [message]),
          returnValue: Future<bool>.value(false)) as _i13.Future<bool>);
  @override
  _i13.Future<String?> getGroupJointToken({_i3.Uid? groupUid}) =>
      (super.noSuchMethod(
          Invocation.method(#getGroupJointToken, [], {#groupUid: groupUid}),
          returnValue: Future<String?>.value()) as _i13.Future<String?>);
  @override
  _i13.Future<String?> getChannelJointToken({_i3.Uid? channelUid}) =>
      (super.noSuchMethod(
          Invocation.method(
              #getChannelJointToken, [], {#channelUid: channelUid}),
          returnValue: Future<String?>.value()) as _i13.Future<String?>);
  @override
  _i13.Future<bool> unpinMessage(_i14.Message? message) =>
      (super.noSuchMethod(Invocation.method(#unpinMessage, [message]),
          returnValue: Future<bool>.value(false)) as _i13.Future<bool>);
}

/// A class which mocks [CoreServices].
///
/// See the documentation for Mockito's code generation for more information.
class MockCoreServices extends _i1.Mock implements _i34.CoreServices {
  @override
  bool get responseChecked => (super
          .noSuchMethod(Invocation.getter(#responseChecked), returnValue: false)
      as bool);
  @override
  set responseChecked(bool? _responseChecked) =>
      super.noSuchMethod(Invocation.setter(#responseChecked, _responseChecked),
          returnValueForMissingStub: null);
  @override
  int get backoffTime =>
      (super.noSuchMethod(Invocation.getter(#backoffTime), returnValue: 0)
          as int);
  @override
  set backoffTime(int? _backoffTime) =>
      super.noSuchMethod(Invocation.setter(#backoffTime, _backoffTime),
          returnValueForMissingStub: null);
  @override
  _i9.BehaviorSubject<_i34.ConnectionStatus> get connectionStatus =>
      (super.noSuchMethod(Invocation.getter(#connectionStatus),
              returnValue: _FakeBehaviorSubject_8<_i34.ConnectionStatus>())
          as _i9.BehaviorSubject<_i34.ConnectionStatus>);
  @override
  set connectionStatus(
          _i9.BehaviorSubject<_i34.ConnectionStatus>? _connectionStatus) =>
      super.noSuchMethod(
          Invocation.setter(#connectionStatus, _connectionStatus),
          returnValueForMissingStub: null);
  @override
  void closeConnection() =>
      super.noSuchMethod(Invocation.method(#closeConnection, []),
          returnValueForMissingStub: null);
  @override
  void gotResponse() => super.noSuchMethod(Invocation.method(#gotResponse, []),
      returnValueForMissingStub: null);
  @override
  dynamic sendMessage(_i35.MessageByClient? message) =>
      super.noSuchMethod(Invocation.method(#sendMessage, [message]));
  @override
  dynamic sendSeen(_i36.SeenByClient? seen) =>
      super.noSuchMethod(Invocation.method(#sendSeen, [seen]));
  @override
  dynamic sendActivity(_i19.ActivityByClient? activity, String? id) =>
      super.noSuchMethod(Invocation.method(#sendActivity, [activity, id]));
  @override
  dynamic messageEdited(_i3.Uid? roomUid, int? id, int? time) => super
      .noSuchMethod(Invocation.method(#messageEdited, [roomUid, id, time]));
  @override
  _i13.Future<dynamic> showNotification(
          _i3.Uid? roomUid, _i35.Message? message) =>
      (super.noSuchMethod(
          Invocation.method(#showNotification, [roomUid, message]),
          returnValue: Future<dynamic>.value()) as _i13.Future<dynamic>);
  @override
  void updateLastActivityTime(
          _i37.LastActivityDao? lastActivityDao, _i3.Uid? userUid, int? time) =>
      super.noSuchMethod(
          Invocation.method(
              #updateLastActivityTime, [lastActivityDao, userUid, time]),
          returnValueForMissingStub: null);
}

/// A class which mocks [QueryServiceClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockQueryServiceClient extends _i1.Mock
    implements _i38.QueryServiceClient {
  @override
  _i10.ResponseFuture<_i38.IdIsAvailableRes> idIsAvailable(
          _i38.IdIsAvailableReq? request,
          {_i10.CallOptions? options}) =>
      (super.noSuchMethod(
              Invocation.method(#idIsAvailable, [request], {#options: options}),
              returnValue: _FakeResponseFuture_9<_i38.IdIsAvailableRes>())
          as _i10.ResponseFuture<_i38.IdIsAvailableRes>);
  @override
  _i10.ResponseFuture<_i38.SetIdRes> setId(_i38.SetIdReq? request,
          {_i10.CallOptions? options}) =>
      (super.noSuchMethod(
              Invocation.method(#setId, [request], {#options: options}),
              returnValue: _FakeResponseFuture_9<_i38.SetIdRes>())
          as _i10.ResponseFuture<_i38.SetIdRes>);
  @override
  _i10.ResponseFuture<_i38.BlockRes> block(_i38.BlockReq? request,
          {_i10.CallOptions? options}) =>
      (super.noSuchMethod(
              Invocation.method(#block, [request], {#options: options}),
              returnValue: _FakeResponseFuture_9<_i38.BlockRes>())
          as _i10.ResponseFuture<_i38.BlockRes>);
  @override
  _i10.ResponseFuture<_i38.UnblockRes> unblock(_i38.UnblockReq? request,
          {_i10.CallOptions? options}) =>
      (super.noSuchMethod(
              Invocation.method(#unblock, [request], {#options: options}),
              returnValue: _FakeResponseFuture_9<_i38.UnblockRes>())
          as _i10.ResponseFuture<_i38.UnblockRes>);
  @override
  _i10.ResponseFuture<_i38.ReportRes> report(_i38.ReportReq? request,
          {_i10.CallOptions? options}) =>
      (super.noSuchMethod(
              Invocation.method(#report, [request], {#options: options}),
              returnValue: _FakeResponseFuture_9<_i38.ReportRes>())
          as _i10.ResponseFuture<_i38.ReportRes>);
  @override
  _i10.ResponseFuture<_i38.GetBlockedListRes> getBlockedList(
          _i38.GetBlockedListReq? request,
          {_i10.CallOptions? options}) =>
      (super.noSuchMethod(
          Invocation.method(#getBlockedList, [request], {#options: options}),
          returnValue:
              _FakeResponseFuture_9<_i38.GetBlockedListRes>()) as _i10
          .ResponseFuture<_i38.GetBlockedListRes>);
  @override
  _i10.ResponseFuture<_i38.GetIdByUidRes> getIdByUid(
          _i38.GetIdByUidReq? request,
          {_i10.CallOptions? options}) =>
      (super.noSuchMethod(
              Invocation.method(#getIdByUid, [request], {#options: options}),
              returnValue: _FakeResponseFuture_9<_i38.GetIdByUidRes>())
          as _i10.ResponseFuture<_i38.GetIdByUidRes>);
  @override
  _i10.ResponseFuture<_i38.GetUidByIdRes> getUidById(
          _i38.GetUidByIdReq? request,
          {_i10.CallOptions? options}) =>
      (super.noSuchMethod(
              Invocation.method(#getUidById, [request], {#options: options}),
              returnValue: _FakeResponseFuture_9<_i38.GetUidByIdRes>())
          as _i10.ResponseFuture<_i38.GetUidByIdRes>);
  @override
  _i10.ResponseFuture<_i38.SearchUidRes> searchUid(_i38.SearchUidReq? request,
          {_i10.CallOptions? options}) =>
      (super.noSuchMethod(
              Invocation.method(#searchUid, [request], {#options: options}),
              returnValue: _FakeResponseFuture_9<_i38.SearchUidRes>())
          as _i10.ResponseFuture<_i38.SearchUidRes>);
  @override
  _i10.ResponseFuture<_i38.GetLastActivityRes> getLastActivity(
          _i38.GetLastActivityReq? request,
          {_i10.CallOptions? options}) =>
      (super.noSuchMethod(
          Invocation.method(#getLastActivity, [request], {#options: options}),
          returnValue:
              _FakeResponseFuture_9<_i38.GetLastActivityRes>()) as _i10
          .ResponseFuture<_i38.GetLastActivityRes>);
  @override
  _i10.ResponseFuture<_i38.FetchMessagesRes> fetchMessages(
          _i38.FetchMessagesReq? request,
          {_i10.CallOptions? options}) =>
      (super.noSuchMethod(
              Invocation.method(#fetchMessages, [request], {#options: options}),
              returnValue: _FakeResponseFuture_9<_i38.FetchMessagesRes>())
          as _i10.ResponseFuture<_i38.FetchMessagesRes>);
  @override
  _i10.ResponseFuture<_i38.CountIsHiddenMessagesRes> countIsHiddenMessages(
          _i38.CountIsHiddenMessagesReq? request,
          {_i10.CallOptions? options}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #countIsHiddenMessages, [request], {#options: options}),
              returnValue:
                  _FakeResponseFuture_9<_i38.CountIsHiddenMessagesRes>())
          as _i10.ResponseFuture<_i38.CountIsHiddenMessagesRes>);
  @override
  _i10.ResponseFuture<_i38.GetAllUserRoomMetaRes> getAllUserRoomMeta(
          _i38.GetAllUserRoomMetaReq? request,
          {_i10.CallOptions? options}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #getAllUserRoomMeta, [request], {#options: options}),
              returnValue: _FakeResponseFuture_9<_i38.GetAllUserRoomMetaRes>())
          as _i10.ResponseFuture<_i38.GetAllUserRoomMetaRes>);
  @override
  _i10.ResponseFuture<_i38.GetUserRoomMetaRes> getUserRoomMeta(
          _i38.GetUserRoomMetaReq? request,
          {_i10.CallOptions? options}) =>
      (super.noSuchMethod(
          Invocation.method(#getUserRoomMeta, [request], {#options: options}),
          returnValue:
              _FakeResponseFuture_9<_i38.GetUserRoomMetaRes>()) as _i10
          .ResponseFuture<_i38.GetUserRoomMetaRes>);
  @override
  _i10.ResponseFuture<_i38.GetMediaMetadataRes> getMediaMetadata(
          _i38.GetMediaMetadataReq? request,
          {_i10.CallOptions? options}) =>
      (super.noSuchMethod(
          Invocation.method(#getMediaMetadata, [request], {#options: options}),
          returnValue:
              _FakeResponseFuture_9<_i38.GetMediaMetadataRes>()) as _i10
          .ResponseFuture<_i38.GetMediaMetadataRes>);
  @override
  _i10.ResponseFuture<_i38.FetchMediasRes> fetchMedias(
          _i38.FetchMediasReq? request,
          {_i10.CallOptions? options}) =>
      (super.noSuchMethod(
              Invocation.method(#fetchMedias, [request], {#options: options}),
              returnValue: _FakeResponseFuture_9<_i38.FetchMediasRes>())
          as _i10.ResponseFuture<_i38.FetchMediasRes>);
  @override
  _i10.ResponseFuture<_i38.FetchMentionListRes> fetchMentionList(
          _i38.FetchMentionListReq? request,
          {_i10.CallOptions? options}) =>
      (super.noSuchMethod(
          Invocation.method(#fetchMentionList, [request], {#options: options}),
          returnValue:
              _FakeResponseFuture_9<_i38.FetchMentionListRes>()) as _i10
          .ResponseFuture<_i38.FetchMentionListRes>);
  @override
  _i10.ResponseFuture<_i38.FetchCurrentUserSeenDataRes>
      fetchCurrentUserSeenData(_i38.FetchCurrentUserSeenDataReq? request,
              {_i10.CallOptions? options}) =>
          (super.noSuchMethod(
                  Invocation.method(#fetchCurrentUserSeenData, [request],
                      {#options: options}),
                  returnValue:
                      _FakeResponseFuture_9<_i38.FetchCurrentUserSeenDataRes>())
              as _i10.ResponseFuture<_i38.FetchCurrentUserSeenDataRes>);
  @override
  _i10.ResponseFuture<
      _i38.FetchLastOtherUserSeenDataRes> fetchLastOtherUserSeenData(
          _i38.FetchLastOtherUserSeenDataReq? request,
          {_i10.CallOptions? options}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #fetchLastOtherUserSeenData, [request], {#options: options}),
              returnValue:
                  _FakeResponseFuture_9<_i38.FetchLastOtherUserSeenDataRes>())
          as _i10.ResponseFuture<_i38.FetchLastOtherUserSeenDataRes>);
  @override
  _i10.ResponseFuture<_i38.FetchSeenCountOfChannelMessageRes>
      fetchSeenCountOfChannelMessage(
              _i38.FetchSeenCountOfChannelMessageReq? request,
              {_i10.CallOptions? options}) =>
          (super.noSuchMethod(
                  Invocation.method(#fetchSeenCountOfChannelMessage, [request],
                      {#options: options}),
                  returnValue: _FakeResponseFuture_9<
                      _i38.FetchSeenCountOfChannelMessageRes>())
              as _i10.ResponseFuture<_i38.FetchSeenCountOfChannelMessageRes>);
  @override
  _i10.ResponseFuture<_i38.FetchUserCallsRes> fetchUserCalls(
          _i38.FetchUserCallsReq? request,
          {_i10.CallOptions? options}) =>
      (super.noSuchMethod(
          Invocation.method(#fetchUserCalls, [request], {#options: options}),
          returnValue:
              _FakeResponseFuture_9<_i38.FetchUserCallsRes>()) as _i10
          .ResponseFuture<_i38.FetchUserCallsRes>);
  @override
  _i10.ResponseFuture<_i38.UpdateMessageRes> updateMessage(
          _i38.UpdateMessageReq? request,
          {_i10.CallOptions? options}) =>
      (super.noSuchMethod(
              Invocation.method(#updateMessage, [request], {#options: options}),
              returnValue: _FakeResponseFuture_9<_i38.UpdateMessageRes>())
          as _i10.ResponseFuture<_i38.UpdateMessageRes>);
  @override
  _i10.ResponseFuture<_i38.DeleteMessageRes> deleteMessage(
          _i38.DeleteMessageReq? request,
          {_i10.CallOptions? options}) =>
      (super.noSuchMethod(
              Invocation.method(#deleteMessage, [request], {#options: options}),
              returnValue: _FakeResponseFuture_9<_i38.DeleteMessageRes>())
          as _i10.ResponseFuture<_i38.DeleteMessageRes>);
  @override
  _i10.ResponseFuture<_i38.AddAvatarRes> addAvatar(_i38.AddAvatarReq? request,
          {_i10.CallOptions? options}) =>
      (super.noSuchMethod(
              Invocation.method(#addAvatar, [request], {#options: options}),
              returnValue: _FakeResponseFuture_9<_i38.AddAvatarRes>())
          as _i10.ResponseFuture<_i38.AddAvatarRes>);
  @override
  _i10.ResponseFuture<_i38.RemoveAvatarRes> removeAvatar(
          _i38.RemoveAvatarReq? request,
          {_i10.CallOptions? options}) =>
      (super.noSuchMethod(
              Invocation.method(#removeAvatar, [request], {#options: options}),
              returnValue: _FakeResponseFuture_9<_i38.RemoveAvatarRes>())
          as _i10.ResponseFuture<_i38.RemoveAvatarRes>);
  @override
  _i10.ResponseFuture<_i38.RemovePrivateRoomRes> removePrivateRoom(
          _i38.RemovePrivateRoomReq? request,
          {_i10.CallOptions? options}) =>
      (super.noSuchMethod(
          Invocation.method(#removePrivateRoom, [request], {#options: options}),
          returnValue:
              _FakeResponseFuture_9<_i38.RemovePrivateRoomRes>()) as _i10
          .ResponseFuture<_i38.RemovePrivateRoomRes>);
  @override
  _i10.ResponseFuture<_i38.SearchInMessagesRes> searchInMessages(
          _i38.SearchInMessagesReq? request,
          {_i10.CallOptions? options}) =>
      (super.noSuchMethod(
          Invocation.method(#searchInMessages, [request], {#options: options}),
          returnValue:
              _FakeResponseFuture_9<_i38.SearchInMessagesRes>()) as _i10
          .ResponseFuture<_i38.SearchInMessagesRes>);
  @override
  _i10.ClientCall<Q, R> $createCall<Q, R>(
          _i10.ClientMethod<Q, R>? method, _i13.Stream<Q>? requests,
          {_i10.CallOptions? options}) =>
      (super.noSuchMethod(
          Invocation.method(
              #$createCall, [method, requests], {#options: options}),
          returnValue: _FakeClientCall_10<Q, R>()) as _i10.ClientCall<Q, R>);
  @override
  _i10.ResponseFuture<R> $createUnaryCall<Q, R>(
          _i10.ClientMethod<Q, R>? method, Q? request,
          {_i10.CallOptions? options}) =>
      (super.noSuchMethod(
          Invocation.method(
              #$createUnaryCall, [method, request], {#options: options}),
          returnValue: _FakeResponseFuture_9<R>()) as _i10.ResponseFuture<R>);
  @override
  _i10.ResponseStream<R> $createStreamingCall<Q, R>(
          _i10.ClientMethod<Q, R>? method, _i13.Stream<Q>? requests,
          {_i10.CallOptions? options}) =>
      (super.noSuchMethod(
          Invocation.method(
              #$createStreamingCall, [method, requests], {#options: options}),
          returnValue: _FakeResponseStream_11<R>()) as _i10.ResponseStream<R>);
}

/// A class which mocks [SharedDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedDao extends _i1.Mock implements _i39.SharedDao {
  @override
  _i13.Future<String?> get(String? key) =>
      (super.noSuchMethod(Invocation.method(#get, [key]),
          returnValue: Future<String?>.value()) as _i13.Future<String?>);
  @override
  _i13.Stream<String?> getStream(String? key, {String? defaultValue}) =>
      (super.noSuchMethod(
          Invocation.method(#getStream, [key], {#defaultValue: defaultValue}),
          returnValue: Stream<String?>.empty()) as _i13.Stream<String?>);
  @override
  _i13.Future<void> put(String? key, String? value) => (super.noSuchMethod(
      Invocation.method(#put, [key, value]),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i13.Future<void>);
  @override
  _i13.Future<void> remove(String? key) => (super.noSuchMethod(
      Invocation.method(#remove, [key]),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i13.Future<void>);
  @override
  _i13.Future<bool> getBoolean(String? key, {bool? defaultValue = false}) =>
      (super.noSuchMethod(
          Invocation.method(#getBoolean, [key], {#defaultValue: defaultValue}),
          returnValue: Future<bool>.value(false)) as _i13.Future<bool>);
  @override
  _i13.Stream<bool> getBooleanStream(String? key,
          {bool? defaultValue = false}) =>
      (super.noSuchMethod(
          Invocation.method(
              #getBooleanStream, [key], {#defaultValue: defaultValue}),
          returnValue: Stream<bool>.empty()) as _i13.Stream<bool>);
  @override
  _i13.Future<void> putBoolean(String? key, bool? value) => (super.noSuchMethod(
      Invocation.method(#putBoolean, [key, value]),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i13.Future<void>);
}

/// A class which mocks [AvatarRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockAvatarRepo extends _i1.Mock implements _i40.AvatarRepo {
  @override
  _i13.Future<void> fetchAvatar(_i3.Uid? userUid, bool? forceToUpdate) =>
      (super.noSuchMethod(
              Invocation.method(#fetchAvatar, [userUid, forceToUpdate]),
              returnValue: Future<void>.value(),
              returnValueForMissingStub: Future<void>.value())
          as _i13.Future<void>);
  @override
  dynamic getAvatarRequest(_i3.Uid? userUid) =>
      super.noSuchMethod(Invocation.method(#getAvatarRequest, [userUid]));
  @override
  _i13.Future<bool> needsUpdate(_i3.Uid? userUid) =>
      (super.noSuchMethod(Invocation.method(#needsUpdate, [userUid]),
          returnValue: Future<bool>.value(false)) as _i13.Future<bool>);
  @override
  _i13.Stream<List<_i21.Avatar?>> getAvatar(
          _i3.Uid? userUid, bool? forceToUpdate) =>
      (super.noSuchMethod(
              Invocation.method(#getAvatar, [userUid, forceToUpdate]),
              returnValue: Stream<List<_i21.Avatar?>>.empty())
          as _i13.Stream<List<_i21.Avatar?>>);
  @override
  _i13.Future<_i21.Avatar?> getLastAvatar(
          _i3.Uid? userUid, bool? forceToUpdate) =>
      (super.noSuchMethod(
              Invocation.method(#getLastAvatar, [userUid, forceToUpdate]),
              returnValue: Future<_i21.Avatar?>.value())
          as _i13.Future<_i21.Avatar?>);
  @override
  _i13.Future<void> setMucAvatar(_i3.Uid? uid, String? path) =>
      (super.noSuchMethod(Invocation.method(#setMucAvatar, [uid, path]),
              returnValue: Future<void>.value(),
              returnValueForMissingStub: Future<void>.value())
          as _i13.Future<void>);
  @override
  String? fastForwardAvatarFilePath(_i3.Uid? userUid) => (super.noSuchMethod(
      Invocation.method(#fastForwardAvatarFilePath, [userUid])) as String?);
  @override
  String getAvatarCacheKey(_i3.Uid? userUid) =>
      (super.noSuchMethod(Invocation.method(#getAvatarCacheKey, [userUid]),
          returnValue: '') as String);
  @override
  _i13.Stream<String> getLastAvatarFilePathStream(
          _i3.Uid? userUid, bool? forceToUpdate) =>
      (super.noSuchMethod(
          Invocation.method(
              #getLastAvatarFilePathStream, [userUid, forceToUpdate]),
          returnValue: Stream<String>.empty()) as _i13.Stream<String>);
  @override
  _i13.Future<void> uploadAvatar(String? path, _i3.Uid? uid) =>
      (super.noSuchMethod(Invocation.method(#uploadAvatar, [path, uid]),
              returnValue: Future<void>.value(),
              returnValueForMissingStub: Future<void>.value())
          as _i13.Future<void>);
  @override
  _i13.Future<bool> addAvatarRequest(_i38.AddAvatarReq? addAvatarReq) =>
      (super.noSuchMethod(Invocation.method(#addAvatarRequest, [addAvatarReq]),
          returnValue: Future<bool>.value(false)) as _i13.Future<bool>);
  @override
  _i13.Future<bool?> deleteAvatar(_i21.Avatar? avatar) =>
      (super.noSuchMethod(Invocation.method(#deleteAvatar, [avatar]),
          returnValue: Future<bool?>.value()) as _i13.Future<bool?>);
}

/// A class which mocks [BlockDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockBlockDao extends _i1.Mock implements _i41.BlockDao {
  @override
  _i13.Future<bool> isBlocked(String? uid) =>
      (super.noSuchMethod(Invocation.method(#isBlocked, [uid]),
          returnValue: Future<bool>.value(false)) as _i13.Future<bool>);
  @override
  _i13.Stream<bool?> watchIsBlocked(String? uid) =>
      (super.noSuchMethod(Invocation.method(#watchIsBlocked, [uid]),
          returnValue: Stream<bool?>.empty()) as _i13.Stream<bool?>);
  @override
  _i13.Future<void> block(String? uid) => (super.noSuchMethod(
      Invocation.method(#block, [uid]),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i13.Future<void>);
  @override
  _i13.Future<void> unblock(String? uid) => (super.noSuchMethod(
      Invocation.method(#unblock, [uid]),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i13.Future<void>);
}
