apiVersion: apps/v1
kind: Deployment
metadata:
  name: deliver-web
spec:
  replicas: 1
  revisionHistoryLimit: 1
  template:
    spec:
      containers:
        - name: deliver-web
          image: CONTAINER_IMAGE
          resources:
            requests:
              memory: "100Mi"
              cpu: "200m"
            limits:
              memory: "100Mi"
              cpu: "200m"
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: deliver-docker-registry