name: we-co
version: 1.9.7
summary: Messenger
description: Messenger

confinement: strict
base: core20
grade: stable

slots:
  dbus-we-co: # adjust accordingly to your app name
    interface: dbus
    bus: session
    name: ir.we.deliver # adjust accordingly to your app name and

apps:
  we-co:
    command: we
    extensions: [gnome-3-38]
    plugs:
      - dbus-we-co


parts:
  we-co:
    source: .
    plugin: nil
    build-packages:
      - cmake
      - clang
      - curl
      - git
      - unzip

    stage-packages:
      - libgstreamer1.0-0
      - libgstreamer-plugins-base1.0-0
      - libgtk-3-dev
    override-build: |
      git clone https://github.com/flutter/flutter.git -b stable
      export PATH="$PATH:`pwd`/flutter/bin"
      flutter doctor
      flutter clean
      flutter pub get
      flutter config --enable-linux-desktop
      sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
      flutter build linux --release -v
      cp -rp $SNAPCRAFT_PART_BUILD/build/linux/x64/release/bundle/* $SNAPCRAFT_PART_INSTALL/
    

#    flutter-target: lib/main.dart # The main entry-point file of the application
