name: we-co
version: 1.9.7
summary: Messenger
description: Messenger

confinement: strict
base: core18
grade: stable

slots:
  dbus-we-co: # adjust accordingly to your app name
    interface: dbus
    bus: session
    name: ir.we.deliver # adjust accordingly to your app name and

apps:
  we-co:
    command: we
    extensions: [ flutter-stable ]
    plugs:
      - dbus-we-co


parts:
  we-co:
    source: .
    plugin: flutter
    build-packages: [ libgstreamer1.0-dev,libgstreamer-plugins-base1.0-dev]

    stage-packages:
      - libgstreamer1.0-0
      - libgstreamer-plugins-base1.0-0
      - libgtk-3-dev

    flutter-target: lib/main.dart # The main entry-point file of the application
