name: deliver-co
version: 1.4.9
summary: Messenger
description: Messenger

confinement: strict
base: core18
grade: stable

slots:
  dbus-deliver-co: # adjust accordingly to your app name
    interface: dbus
    bus: session
    name: ir.we.deliver # adjust accordingly to your app name and

apps:
  deliver-co:
    command: deliver
    extensions: [flutter-master]
    plugs:
      - home
      - network
      - system-packages-doc
    slots:
      - dbus-deliver-co

parts:
  deliver-co:
    stage-packages:
      - vlc
      - libvlc-dev
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application
